*manage: - setting schedule to "disabled" now only affects ip list autoupdates. nopersistence value is only set during installation. - updated the "usage" function to reflect the changes - improved the "usage" function output - changed the logic preceding calling *cronsetup to accomodate the changes - call *cronsetup without arguments (parameters are communicated via the config file) - die with error if *cronsetup returns error - improved a console output message

diff --git a/geoblocker_bash-manage b/geoblocker_bash-manage
--- a/geoblocker_bash-manage
+++ b/geoblocker_bash-manage
@@ -48,19 +48,20 @@ WARNING: if removing a whitelist: Geoblocking will remain active after removal.
 Usage: $me -a <action> [-l <list_type>] [-c "[tld] [tld] ... [tld]"] [-s <"sch_expression"|disable>] [-f] [-t] [-d] [-h]
 
 Options:
-    -a add|remove|schedule        : action to perform: add or remove ipsets, iptables rules and cron jobs
-                                       or "schedule" to change the cron schedule (has no effect on iptables rules).
-    -l <list_type>                : apply list type: whitelist|blacklist
+    -a <add|remove|schedule>        : action to perform: add or remove ipsets, iptables rules and cron jobs
+                                          or "schedule" to change the cron schedule (has no effect on iptables rules).
+    -l <list_type>                  : apply list type: whitelist|blacklist
 
-    -c "tld(s)"                   : tld / country codes. if passing multiple country codes, use double quotes.
-    -s <"sch_expression">|disable : schedule expression for the periodic cron job, must be inside double quotes.
-                                       "disable" removes cron jobs and turns off persistence.
+    -c "tld(s)"                     : tld / country codes. if passing multiple country codes, use double quotes.
+    -s <"sch_expression"|disable>   : schedule expression for the periodic cron job implementing auto-updates of the ip lists,
+                                          must be inside double quotes.
+                                    -- default: "0 4 * * *" (at 4:00 [am] every day)
+                                    -- "disable" will *skip* creating the cron job which is required for automatic updates of the ip list
 
-    -f                            : Force the action even if it doesn't make sense or may cause remote server lockout.
-
-    -t                            : Test mode: inject unexpected tld and verify fault recovery
-    -d                            : Debug
-    -h                            : This help
+    -f                              : Force the action even if it doesn't make sense or may cause remote server lockout.
+    -t                              : Test mode: inject unexpected tld and verify fault recovery
+    -d                              : Debug
+    -h                              : This help
 
 EOF
 }
@@ -105,7 +106,7 @@ debugentermsg
 restore_from_config() {
 # restore tlds from the config file
 
-	echo "Re-applying previous countries set: '$config_tlds'... "
+	echo "Restoring countries set '$config_tlds' from the config file... "
 	$run_command -o -a "remove" -c "$config_tlds $unexpected_tlds $tlds_to_change"
 	[[ "$config_tlds" != "" ]] && $run_command -o -a "add" -c "$config_tlds"
 
@@ -336,29 +337,17 @@ if [ "$action" != "schedule" ]; then
 	debugprint "Skipping cron setup because action is not 'schedule'."
 else
 
-	# translate *manage arguments into *cronsetup arguments
-	# can't send empty $cron_schedule argument because of getopts issues with empty arguments
-	if [ "$cron_schedule" = "disable" ]; then
-		cron_action="disable"
-		cron_schedule="disable"
-	else cron_action="apply"
-	fi
+	[[ "$cron_schedule" == "" ]] && cron_schedule="disable"
 
-	[ -z "$cron_schedule" ] && cron_schedule="disable"
+	# write to the config file in order to communicate parameters to *cronsetup
+	setconfig "CronSchedule=$cron_schedule" || { die -nolog "Failed to write the updated CronSchedule value to the config file"; }
 
-	# check that countries list in config is not empty
-	config_tlds="$(getconfig "Countries")" || { die -nolog "Error: Couldn't read value for Countries from the config file."; }
-
-	if [ -z "$config_tlds" ]; then
-		die -nolog "Error: Countries list in the config file is empty! No point in creating cron jobs."
+	${suite_name}-cronsetup; rv=$?
+	echo
+	if [ "$rv" -eq 0 ]; then
+		echo "View current cron jobs with 'sudo crontab -l'"
 	else
-		${suite_name}-cronsetup -a "$cron_action" -s "$cron_schedule"; rv=$?
-		echo
-		if [ "$rv" -eq 0 ]; then
-			echo "View current cron jobs with 'sudo crontab -l'"
-		else
-			echo "Error: Failed to create cron jobs!"
-		fi
+		die -nolog "Error: Failed to create cron jobs!"
 	fi
 fi
 
