*manage: multiple changes - source the new *common script - moved some functions and variables to the *common script - moved arguments sanitization to the *common script - replaced the hard-coded suite name with a variable - improved debug messages - improved some code comments - removed a completed TODO - don't call the backup script on the "schedule" action

diff --git a/geoblocker_bash-manage b/geoblocker_bash-manage
--- a/geoblocker_bash-manage
+++ b/geoblocker_bash-manage
@@ -16,23 +16,12 @@
 
 # 'geoblocker_bash-manage -a schedule -s <schedule_expression>' : changes the schedule for the periodic cron job.
 
-me=$(basename "$0")
-parent_script="$(ps -o args= $PPID | awk -v RS='/| ' '/^geoblocker/')"
+suite_name="geoblocker_bash"
+script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+[ -n "$script_dir" ] && cd "$script_dir" || { echo "Error: Couldn't cd into '$script_dir'. Exiting"; exit 1; }
 
-# arguments sanitization
-arguments=()
-for arg in "$@"; do
-	# trim single-quotes if any
-	arg="${arg//\'}";
-	# trim double-quotes if any
-	arg="${arg//\"}"
-	# trim leading and trailing whitespaces
-	arg="$(awk '{$1=$1};1' <<< "$arg")"
-	# add to array while discarding empty arguments
-	[ -n "$arg" ] && arguments+=("$arg")
-done
-# replace arguments with sanitized ones
-set -- "${arguments[@]}"
+source "${suite_name}-common" || { echo "Error: Can't find ${suite_name}-common. Exiting"; exit 1; }
+# **NOTE** that some functions and variables are sourced from the *common script
 
 #### USAGE
 
@@ -83,71 +72,16 @@ while getopts "a:c:s:fnpdh" opt; do
 done
 shift $((OPTIND -1))
 
+echo ""
+
+# Print script enter message for debug
+debugentermsg
+
 
 #### FUNCTIONS
 
-debugprint() {
-# prints a debug message
-	[ "$debug" ] && echo -e "    Debug: $*"
-}
-
-echo ""
-
-argsmsg="Started *manage with args: $(for arg in "${arguments[@]}"; do echo -n "'$arg'  "; done; echo)"
-debugprint "\033[1;33m${argsmsg}\033[0m"
-
-die() {
-	# if first arg is a number, assume it's the exit code
-	if [[ "$1" =~ ^[0-9]+$ ]]; then rv="$1"; shift; else rv="1"; fi
-    if [ -n "$*" ]; then
-        echo "" 1>&2
-		# loop through arguments and print them to stderr and to the syslog
-        for arg in "$@"; do
-            echo "$arg" 1>&2
-            logger -t "$me" "$arg"
-        done
-    fi
-    [ -n "$parent_script" ] && debugprint "\033[1;33mBack to $parent_script...\033[0m"
-    echo "" 1>&2
-    exit "$rv"
-}
-
-getconfig() {
-# reads a field named $1 from the config file $2
-# outputs the resulting field
-# returns 0 if successful, 1 if not
-	fieldname="$1"
-	configfile="$2"
-	if [ -z "$fieldname" ] || [ -z "$configfile" ]; then return 1; fi
-	field="$(grep "$fieldname=" "$configfile" | sed "s/.*$fieldname=//")"; rv=$?
-	if [ -z "$field" ]; then
-		echo ""
-		rv=$((rv + 1))
-	else
-		echo "$field"
-	fi
-	return $rv
-}
-
-setconfig() {
-# changes a field named $1 in the config file $2 to value $3
-# returns 0 if successful, 1 if not
-	fieldname="$1"
-	configfile="$2"
-	field="$3"
-	if [ -z "$fieldname" ] || [ -z "$configfile" ]; then return 1; fi
-
-	# remove corresponding config line
-	grep -v "$fieldname=" "$configfile" > "${configfile}.temp"
-	mv "${configfile}.temp" "$configfile"
-
-	# add updated config line
-	echo -e "$fieldname=$field" >> "$configfile"; rv=$?
-	return $rv
-}
-
 find_lists_intersection() {
-# finds duplicates-free intersection between fields in input strings $1 and $2,
+# finds duplicates-free intersection between space-delimited fields in input strings $1 and $2,
 #      and outputs the intersection as a string
 
 	str1="$1"; str2="$2"
@@ -159,7 +93,8 @@ find_lists_intersection() {
 }
 
 find_lists_difference() {
-# finds fields that exist in lists $1 and $2 but not both and outputs the difference as a string
+# finds space-delimited fields that exist in strings $1 or $2 but not both
+#      and outputs the difference as a string
 
 	str1="$1"; str2="$2"
 	result_str="$(comm -3 <(echo "$str1" | tr ' ' '\n' | sort -u) \
@@ -170,7 +105,7 @@ find_lists_difference() {
 }
 
 remove_a_from_b() {
-# removes all fields found in string $1 from string $2, outputs the result as a string
+# removes all space-delimited fields found in string $1 from string $2, outputs the result as a string
 
 	str1="$1"; str2="$2"
 	while read -r field_str; do
@@ -183,29 +118,24 @@ remove_a_from_b() {
 
 #### VARIABLES
 
-#convert country codes to lower case
-tlds_arg="${tlds_arg,,}"
-
-conf_dir="/etc/geoblocker_bash"
-conf_file="${conf_dir}/geoblocker_bash.conf"
-
-# get datadir from the config file
-datadir="$(getconfig "Datadir" "$conf_file")"
-
 # get install_dir from the config file
 install_dir="$(getconfig "Installdir" "$conf_file")"
 
-tlds_status_file="$datadir/tlds_status"
+#convert country codes to lower case
+tlds_arg="${tlds_arg,,}"
 
 # get sleeptime (for reboot) from the config file
 sleeptime="$(getconfig "RebootSleepTime" "$conf_file")"
 
-run_command="${install_dir}/geoblocker_bash-run"
+run_command="${install_dir}/${suite_name}-run"
+
+# get datadir from the config file
+datadir="$(getconfig "Datadir" "$conf_file")"
+
+tlds_status_file="$datadir/tlds_status"
 
 
 #### CHECKS
-
-# TODO: test empty "action" etc
 
 # check for root
 if [ "$EUID" -ne 0 ]; then
@@ -377,7 +307,7 @@ else
 		else
 			echo "Failed to re-apply previous countries set." >&2
 			# call the *backup script to initiate recovery from fault
-			geoblocker_bash-backup -r "$debug"
+			${suite_name}-backup -r "$debug"
 			die 1 ""
 		fi
 	fi
@@ -415,7 +345,7 @@ fi
 
 ## Remove current cron jobs
 echo ""
-echo "Removing cron jobs for geoblocker_bash..."
+echo "Removing cron jobs for ${suite_name}..."
 crontab -u root -l 2>/dev/null | grep -v "\"$run_command\"" | sudo crontab -u root -
 
 
@@ -474,14 +404,15 @@ else
 fi
 echo ""
 
-# call the backup script to create a known-good backup of config, ipsets and iptables state
-geoblocker_bash-backup "$debug" -b
+# call the backup script
+[[ "$action" = "add" || "$action" = "remove" ]] && ${suite_name}-backup "$debug" -b
 
 
 echo ""
 echo "View iptables rules with 'sudo iptables -L'"
 echo "View cron jobs with 'sudo crontab -l'"
+echo
 
-[ -n "$parent_script" ] && debugprint "\033[1;33mBack to $parent_script...\033[0m"
+debugexitmsg
 
 exit 0
