geoblocker_bash-manage: mostly re-written to support multiple countries

diff --git a/geoblocker_bash-manage b/geoblocker_bash-manage
--- a/geoblocker_bash-manage
+++ b/geoblocker_bash-manage
@@ -13,17 +13,17 @@ usage() {
     cat <<EOF
 
 This script:
-    Allows to add or delete a whitelist for the specified country to/from geoblocking rules
+    Allows to add or delete whitelists for the specified countries to/from geoblocking rules
         and creates/deletes associated cron jobs.
 
 WARNING if removing a whitelist: Geoblocking will remain active after removal.
 		If you remove your country's whitelist, you may lose remote access to the system.
         
 
-    Usage: $me -c <tld> -a <add|remove> [-s "<schedule>"] [-n] [-d] [-h]
+    Usage: $me -c <"tld [tld] ... [tld]"> -a <add|remove> [-s "<schedule>"] [-n] [-d] [-h]
 
     Options:
-        -c <tld>        : tld / country code for the country to add/remove the whitelist for
+        -c <tld>        : tld / country codes. if passing multiple country codes, use double quotes
         -a <action>     : action to perform: "add" or "remove" associated rules and cron jobs
         -s "<schedule>" : schedule expression for the cron job, must be inside double quotes
 
@@ -38,7 +38,7 @@ EOF
 
 while getopts "c:a:s:ndh" opt; do
 	case $opt in
-		c) country=$OPTARG;;
+		c) countries=$OPTARG;;
 		a) action=$OPTARG;;
 		s) cron_schedule=$OPTARG;;
 		n) no_persistence=true;;
@@ -63,11 +63,21 @@ get_script_dir () {
 	echo "$DIR"
 }
 
+get_config() {
+# reads a field named $1 from the config file $2
+# returns 0 if successful, 1 if not
+	fieldname="$1"
+	configfile="$2"
+	read -r field < <(grep "$fieldname=" "$conf_file" | sed 's/.*$fieldname=//'); rv=$?
+	echo "$field"
+	return rv
+}
+
 #### Checks
 
-if [ -z "$country" ]; then
+if [ -z "$countries" ]; then
 	usage
-	echo "Specify country with \"-c <country>\"!"
+	echo "Specify countries with \"-c <countries>\"!"
 	echo ""
 	exit 1
 fi
@@ -95,8 +105,8 @@ fi
 
 ### Initialize variables
 
-#convert country code to lower case
-country=echo "${country,,}"
+#convert country codes	 to lower case
+countries=echo "${countries,,}"
 
 # TODO: implement config saving in the *install script
 
@@ -104,41 +114,32 @@ conf_dir="/etc/geoblocker_bash"
 conf_file="${conf_dir}/geoblocker_bash.conf"
 
 # read datadir from the config file
-read -r datadir < <(grep -Po 'Datadir=\K.*' "$conf_file")
+datadir="$(getconfig "Datadir" "$conf_file")
 
 # read sleeptime (for reboot) from the config file
-read -r sleeptime < <(grep -Po 'RebootSleep=\K.*' "$conf_file")
+sleeptime="$(getconfig "RebootSleepTime" "$conf_file")
 
 preinstall_policies_file="$datadir/preinstall_policies.bak"
 knowngood_file="$datadir/iptables_knowngood.bak"
 whitelist_dir="$datadir/ip_lists"
-whitelist_file="$whitelist_dir/$country.list"
 
 # get the script path
 read -r scriptdir < <(get_script_dir)
 
 run_command="${scriptdir}/geoblocker_bash-run"
-run_args="-c \"$country\" -w \"$whitelist_dir\" -b \"$knowngood_file\""
-run_args_reboot="${run_args} -s"
 
 echo ""
 
 # cd into script directory
-scriptdir="$(get_script_dir)"
-
 # exit in case "cd" fails
+scriptdir="$(get_script_dir)"
 cd "$scriptdir" || echo "Error: could not change directory to \"$scriptdir\". Exiting."; exit 1
 
 if [ ! "$no_persistence" ] && [ "$action" = "add" ]; then
 
-	# if cron_schedule wasn't provided in args, try getting schedule for this country from the config file
+	# if cron_schedule wasn't provided in args, use the default schedule from the config file
 	if [ -z "$cron_schedule" ]; then
-		read -r cron_schedule < <(grep -Po 'Schedule_${country}=\K.*' "$conf_file")
-	fi
-
-	# if that didn't work, use the default schedule from the config file
-	if [ -z "$cron_schedule" ]; then
-		read -r cron_schedule < <(grep -Po 'Default_schedule=\K.*' "$conf_file")
+		cron_schedule=$(get_config "Default_schedule" "$conf_file")
 	fi
 
 	# validate cron schedule
@@ -166,79 +167,100 @@ fi
 
 #### Main
 
+### Get current set of countries from the the config file into array curr_countries
+curr_countries=( $(getconfig "$Countries" "$conf_file") )
+
+# Get new set of countries from the argument into array arg_countries
+arg_countries=( $(echo "$countries") )
+
+case "$action" in
+	add) 
+		# merge curr_countries and arg_countries arrays into new_countries array while removing duplicates
+		new_countries=( $(printf '%s\n'  "${curr_countries[@]}" "${new_countries[@]}" | sort -ibu) )
+
+		# countries_to_change should contain countries that are not in curr_countries
+		countries_to_change_str="$(arg_countries[@])"
+		for item in "${curr_countries[@]}"; do
+			# compare $item with every element of countries_to_change and remove exact matches in countries_to_change
+			countries_to_change_str=${countries_to_change//$item/}
+		done
+		# convert to array while removing duplicates
+		countries_to_change=( $(echo "$countries_to_change_str" | sort -ibu) )
+	;;
+	remove)
+		# convert to string
+		new_countries_str="${curr_countries[@]}"
+		for item in "${arg_countries[@]}"; do
+			# compare $item with every element of new_countries_str and remove exact matches in new_countries_str
+			new_countries_str=${new_countries_str//$item/}
+		done
+		# convert to array while removing duplicates
+		new_countries=( $(echo "$new_countries_str" | sort -ibu) )
+
+		 # find intersection between the 2 arrays so later we know what countries to remove
+		 read -r -d '' -a countries_to_change < <(join <(printf %s\\n "${curr_countries[@]}" | sort -u) \
+                          <(printf %s\\n "${arg_countries[@]}" | sort -u))
+	;;
+esac
+
 ### Remove cron jobs
 
 echo ""
-echo "Removing cron jobs for country \"$country\"..."
-crontab -u root -l 2>/dev/null | grep -v "reboot sleep .* && \"$run_command\" -c \"$country\"" | sudo crontab -u root -
-crontab -u root -l 2>/dev/null | grep -v "\"$run_command\"  -c \"$country\"" | sudo crontab -u root -	
-
-# TODO: add -r option to *apply
-
-if [ "$action" = "remove" ]; then
-	geoblocker_bash-apply $debug -r -f "$whitelist_file" -b "$knowngood_file"; rv=$?
-	if [ $rv -ne 0 ]; then
-		echo ""
-		exit 1
-	else
-		[ $debug ] && echo "Successfully removed rules for country \"$country\"."
-	fi
-else
+echo "Removing cron jobs for geoblocker_bash..."
+crontab -u root -l 2>/dev/null | grep -v "\"$run_command\"" | sudo crontab -u root -	
 
 ### Fetch and apply the whitelist
 
-	echo "$run_command $debug $run_args" | bash; rv=$?
+# TODO: add -r option to *apply
 
-	if [ $rv -ne 0 ]; then
-		echo "Error running \"$run_command $debug $run_args\". Exiting"
-		echo ""
-		exit 1
-	fi
+echo $run_command $debug -a "$action" -c "$countries_to_change" | bash; rv=$?
+if [ $rv -ne 0 ]; then
+	echo ""
+	exit 1
+else
+	[ $debug ] && echo "Successfully changed rules for countries \"$countries_to_change\"."
+fi
 
-
-	# if no persistence was requested, skip adding cron jobs
-	if [ ! "$no_persistence" ]; then
+# if no persistence was requested, skip adding cron jobs
+if [ ! "$no_persistence" ]; then
 
 ### Create cron jobs
 
-		[ $debug ] && echo ""
-		echo -n "Creating periodic cron job... "
-		echo -e "$(sudo crontab -u root -l 2>/dev/null)\n$cron_schedule \"$run_command\" $run_args &>/dev/null" | sudo crontab -u root -
-		rv=$?
+	[ $debug ] && echo ""
+	echo -n "Creating periodic cron job... "
+	echo -e "$(sudo crontab -u root -l 2>/dev/null)\n$cron_schedule \"$run_command\" -a "apply" &>/dev/null" | sudo crontab -u root -
+	rv=$?
 
-		if [ $rv -ne 0 ]; then
-			echo "Error running crontab command." >&2
-			echo ""
-			exit 1
-		else
-			echo "Success."
-			cron_line_result=$(crontab -u root -l 2>/dev/null |  grep  "\"$run_command\" $run_args")
-			echo "Cron line: \"$cron_line_result\""
-		fi
-
-		[ $debug ] && echo ""
-		echo -n "Creating reboot cron job... "
-
-		# using the -s switch for the *run script to skip fetching at reboot
-		## otherwise if there was no internet connection at reboot time, *fetch would fail which would cause *run to fail,
-		## so *apply wouldn't run, which would leave the system without geoblocking rules
-
-		echo -e "$(sudo crontab -u root -l 2>/dev/null)\n@reboot sleep $sleeptime && \"$run_command\" $run_args_reboot &>/dev/null" | sudo crontab -u root -
-		rv=$?
-
-		if [ $rv -ne 0 ]; then
-			echo "Error running crontab command." >&2
-			echo ""
-			exit 1
-		else
-			echo "Success."
-			cron_line_result=$(crontab -u root -l 2>/dev/null |  grep "reboot sleep .* && \"$run_command\" $run_args_reboot")
-			echo "Reboot cron line: \"$cron_line_result\""
-			echo ""
-			echo "View cron jobs with \"sudo crontab -l\""
-		fi
+	if [ $rv -ne 0 ]; then
+		echo "Error running crontab command." >&2
+		echo ""
+		exit 1
 	else
-		echo "NOTE: No persistence was requested, skipping cron jobs creation."
+		echo "Success."
+		cron_line_result=$(crontab -u root -l 2>/dev/null |  grep  "\"$run_command\"")
+		echo "Cron line: \"$cron_line_result\""
 	fi
-fi
 
+	[ $debug ] && echo ""
+	echo -n "Creating reboot cron job... "
+
+	# using the -s switch for the *run script to skip fetching at reboot
+	## otherwise if there was no internet connection at reboot time, *fetch would fail which would cause *run to fail,
+	## so *apply wouldn't run, which would leave the system without geoblocking rules
+	echo -e "$(sudo crontab -u root -l 2>/dev/null)\n@reboot sleep $sleeptime && \"$run_command\" -a apply -s &>/dev/null" | \
+                sudo crontab -u root -; rv=$?
+
+	if [ $rv -ne 0 ]; then
+		echo "Error running crontab command." >&2
+		echo ""
+		exit 1
+	else
+		echo "Success."
+		cron_line_result=$(crontab -u root -l 2>/dev/null |  grep "reboot sleep .* && \"$run_command\"")
+		echo "Reboot cron line: \"$cron_line_result\""
+		echo ""
+		echo "View cron jobs with \"sudo crontab -l\""
+	fi
+else
+	echo "NOTE: No persistence was requested, skipping cron jobs creation."
+fi
