*fetch: - avoid writing some errors to syslog when run in manual mode - improved error message when invalid action is specified

diff --git a/geoblocker-bash-fetch b/geoblocker-bash-fetch
--- a/geoblocker-bash-fetch
+++ b/geoblocker-bash-fetch
@@ -22,15 +22,18 @@ me=$(basename "$0")
 [ "$EUID" -ne 0 ] && {
 	err="Error: $me needs to be run as root."
 	echo "$err" >&2
-	logger "$err"
+	[ ! "$manualmode" ] && logger "$err"
 	exit 1
 }
 
 suite_name="geoblocker-bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-[ -n "$script_dir" ] && cd "$script_dir" || { err="Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; logger "$err" exit 1; }
+[ -n "$script_dir" ] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
+	[ ! "$manualmode" ] && logger "$err"; exit 1; }
 
-source "$script_dir/${suite_name}-common" || { err="Error: Can't find ${suite_name}-common."; echo >&2; logger "err"; exit 1; }
+source "$script_dir/${suite_name}-common" || { err="$me: Error: Can't source ${suite_name}-common."; echo "$err" >&2; \
+	[ ! "$manualmode" ] && logger "$err"; exit 1; }
+
 # **NOTE** that some functions and variables are sourced from the *common script
 
 # sanitize arguments
@@ -72,7 +75,7 @@ while getopts ":c:p:fdh" opt; do
 		f) force_update="true";;
 		d) debugmode_args="true";;
 		h) usage; exit 0;;
-		\?) usage; die "Error: Unknown option: '-$OPTARG'.";;
+		\?) usage; die "Error: Unknown option: '$OPTARG'.";;
 	esac
 done
 shift $((OPTIND -1))
