*backup: - removed stale code - use check_deps() to check dependencies - minor code cleanup

diff --git a/geoblocker-bash-backup b/geoblocker-bash-backup
--- a/geoblocker-bash-backup
+++ b/geoblocker-bash-backup
@@ -103,23 +103,6 @@ debugentermsg
 
 #### FUNCTIONS
 
-# not needed anymore but leaving it in for now
-restart_fail2ban() {
-# fail2ban doesn't handle well flushing the INPUT chain then restoring iptables
-# this function restarts fail2ban service after these operations in order to work around that issue
-	systemctl is-enabled fail2ban &> /dev/null; rv=$?
-	if [ $rv -eq 0 ]; then
-		echo -n "Restarting fail2ban..." >&2
-		systemctl restart fail2ban; rv=$?
-		if [ $rv -eq 0 ]; then
-			echo "Ok." >&2
-		else
-			echo "Failed." >&2
-		fi
-	fi
-	echo ""
-}
-
 restore_from_file() {
 # restores iptables and ipset state from a backup file
 	restoretarget="$1"
@@ -147,8 +130,6 @@ restore_from_file() {
 		if [ $rv -eq 0 ]; then
 			echo "Success."
 
-# not needed anymore
-#			if [ "$restoretarget" = "iptables" ]; then restart_fail2ban; fi
 			return 0
 		else
 			echo "Failure." >&2
@@ -171,18 +152,16 @@ restore_from_file() {
 		echo "WARNING: RECOVERY TEST FAILED AND GEOBLOCKER IS CURRENTLY INACTIVE" >&2
 
 		if [ "$restoretarget" = "iptables" ]; then
-# not needed anymore
-#			restart_fail2ban
-			die 1 -nolog
+			die -nolog
 		fi
 	fi
-	echo ""; echo ""
+	echo -e "\n"
 }
 
 restoreknowngood() {
 # resets iptables policies and rules, destroys all associated ipsets and then initiates restore from file
 	restorefile="$1"
-	echo; echo
+	echo -e "\n"
 	echolog -err "NOTE: Resetting iptables rules for ${suite_name}."
 
 	echo "Setting INPUT chain policy to ACCEPT... "
@@ -210,15 +189,14 @@ restoreknowngood() {
 	done
 
 	echo "NOTE: Restoring last known-good ipset and iptables from backup... " >&2
-	echo "Backup file: $restorefile" >&2
-	echo ""
+	echo -e "Backup file: $restorefile\n" >&2
 
 	restore_from_file "ipset" "$restorefile"
 	restore_from_file "iptables" "$restorefile"
 }
 
 knowngood_failed() {
-	echo ""
+	echo
 	echolog -err "$1" "$2"
 	if [[ "$emergency_deactivation" != "" ]]; then ${suite_name}-reset; fi
 	debugexitmsg
@@ -242,6 +220,8 @@ knowngood_file="$datadir/iptables_knowngood.bak"
 
 #### CHECKS
 
+missing_deps="$(check_deps iptables-save iptables-restore ipset)" || die "Error: missing dependencies: $missing_deps."
+
 # check that the config file exists
 [ ! -f "$conf_file" ] && die "Config file '$conf_file' doesn't exist! Run the installation script again."
 
@@ -250,24 +230,9 @@ if [ -z "$knowngood_file" ]; then
 	die "Error: Could not read the backup file path from config."
 fi
 
-# Check for ipset utility
-if ! command -v "ipset" &> /dev/null; then
-	die "Error: Can not find 'ipset'. Install it with 'apt install ipset' or similar."
-fi
-
-# Check for iptables-save utility
-if ! command -v "iptables-save" &> /dev/null; then
-	die "Error: Can not find 'iptables-save'."
-fi
-
-# Check for iptables-restore utility
-if ! command -v "iptables-restore" &> /dev/null; then
-	die "Error: Can not find 'iptables-restore'."
-fi
-
 # check for valid action
 
-[ -z "$action" ] && { usage; die 1 "Specify action!"; }
+[ -z "$action" ] && { usage; die "Specify action!"; }
 
 case "$action" in
 	create-backup) ;;
@@ -309,8 +274,7 @@ if [ "$action" = "create-backup" ]; then
 	mv "$knowngood_file.new" "$knowngood_file"; rv=$?
 	[ "$rv" -ne 0 ] && die "Error overwriting the backup file."
 
-	echo ""
-	echo "Successfully created backup of config, ipsets and iptables rules."
+	echo -e "\nSuccessfully created backup of config, ipsets and iptables rules."
 	echo "Backup file: '$knowngood_file'"
 fi
 
