multiple scripts: - use '[[ ]]' bash built-in instead of '[ ]' - minor code style improvements

diff --git a/geoblocker-bash-apply b/geoblocker-bash-apply
--- a/geoblocker-bash-apply
+++ b/geoblocker-bash-apply
@@ -15,20 +15,20 @@
 me=$(basename "$0")
 
 # check for root
-[ "$EUID" -ne 0 ] && {
+[[ "$EUID" -ne 0 ]] && {
 	err="Error: $me needs to be run as root."
 	echo "$err" >&2
-	[ ! "$nolog" ] && logger "$err"
+	[[ ! "$nolog" ]] && logger "$err"
 	exit 1
 }
 
 suite_name="geoblocker-bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-[ -n "$script_dir" ] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
-	[ ! "$nolog" ] && logger "$err"; exit 1; }
+[[ -n "$script_dir" ]] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
+	[[ ! "$nolog" ]] && logger "$err"; exit 1; }
 
 source "$script_dir/${suite_name}-common" || { err="$me: Error: Can't source ${suite_name}-common."; echo "$err" >&2; \
-	[ ! "$nolog" ] && logger "$err"; exit 1; }
+	[[ ! "$nolog" ]] && logger "$err"; exit 1; }
 
 # **NOTE** that some functions and variables are sourced from the *common script
 
@@ -70,7 +70,7 @@ EOF
 action="$1"
 shift 1
 
-[ -z "$action" ] && { usage; die 1 "Specify action!"; }
+[[ -z "$action" ]] && { usage; die 1 "Specify action!"; }
 
 # check for valid action
 case "$action" in
@@ -90,7 +90,7 @@ while getopts ":c:dht" opt; do
 done
 shift $((OPTIND -1))
 
-[[ "$*" != "" ]] && {
+[[ -n "$*" ]] && {
 	usage
 	err1="Error in arguments. First unrecognized argument: '$1'."
 	err2="Note: If specifying multiple country codes, put them in double quotation marks."
@@ -130,6 +130,35 @@ destroy_temp_ipsets() {
 	done
 }
 
+getlocalsubnet() {
+# attempts to find local subnet for the main network interface
+
+	# regex patterns used for ipv4 validation
+	# using Perl regex syntax because grep is faster with it than with native grep syntax
+	# regex compiled from 2 suggestions found here:
+	# https://stackoverflow.com/questions/5284147/validating-ipv4-addresses-with-regexp
+	ip_regex='^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}'
+	mask_regex='(/([01]?\d\d?|2[0-4]\d|25[0-5]))$'
+	subnet_regex="${ip_regex}${mask_regex}"
+
+	# returns local ip with subnet mask
+	localip="$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}')"
+
+	# Change last ipv4 octet to 0
+	lsubnet="$(printf "%s" "$localip" | sed 's|\([0-9]*\.[0-9]*\.[0-9]*\.\)[0-9]*|\10|')"
+
+	# Verifies that the argument is a valid ipv4 subnet
+	printf "%s" "$lsubnet" | grep -P "$subnet_regex" &>/dev/null; rv=$?
+
+	if [[ $rv -ne 0 ]]; then
+		# if validation fails, output empty string
+		printf "%s" ""
+	else
+		printf "%s" "$lsubnet"
+	fi
+	return $rv
+}
+
 
 #### VARIABLES
 
@@ -161,20 +190,20 @@ exitvalue="0"
 missing_deps="$(check_deps iptables-save iptables-restore ipset)" || die "Error: missing dependencies: $missing_deps."
 
 # check that the config file exists
-[ ! -f "$conf_file" ] && die "Config file '$conf_file' doesn't exist! Run the installation script again."
+[[ ! -f "$conf_file" ]] && die "Config file '$conf_file' doesn't exist! Run the installation script again."
 
 # check for country tlds
-[ -z "$tlds" ] && { usage; die 254 "Specify country codes!"; }
+[[ -z "$tlds" ]] && { usage; die 254 "Specify country codes!"; }
 
 # check for datadir path
-[ -z "$datadir" ] && die 254 "Error: failed to read the 'datadir' variable from the config file."
+[[ -z "$datadir" ]] && die 254 "Error: failed to read the 'datadir' variable from the config file."
 
-[ -z "$list_type" ] && die "\$list_type variable should not be empty! Something is wrong!"
+[[ -z "$list_type" ]] && die "\$list_type variable should not be empty! Something is wrong!"
 
 
 #### MAIN
 
-if [ "$action" = "add" ]; then
+if [[ "$action" = "add" ]]; then
 ### create temporary ipsets and load ip lists into them
 
 	for tld in $tlds; do
@@ -182,7 +211,7 @@ if [ "$action" = "add" ]; then
 		temp_ipset="${suite_name}_${tld}_temp"
 
 		# check that the iplist file exists
-		[ ! -f "$iplist_file" ] && die 254 "Error: Can not find the iplist file in path: '$iplist_file'."
+		[[ ! -f "$iplist_file" ]] && die 254 "Error: Can not find the iplist file in path: '$iplist_file'."
 
 		# first destroy temporary ipset with that name in case it exists
 		ipset destroy "$temp_ipset" &>/dev/null
@@ -198,7 +227,7 @@ if [ "$action" = "add" ]; then
 		# set hashsize to (512) or (ipset_maxelements / 4), whichever is larger
 		prelim_hashsize=$(echo "scale=0 ; $ipset_maxelem / 4" | bc)
 	#	debugprint "calculated hashsize: $prelim_hashsize"
-		if [ "$prelim_hashsize" -lt 512 ]; then
+		if [[ "$prelim_hashsize" -lt 512 ]]; then
 			ipset_hash=512
 		else
 			ipset_hash="$prelim_hashsize"
@@ -208,7 +237,7 @@ if [ "$action" = "add" ]; then
 		# create new temporary ipset
 		debugprint "Creating new ipset '$temp_ipset'... "
 		ipset create "$temp_ipset" hash:net family "$family" hashsize "$ipset_hash" maxelem "$ipset_maxelem"; rv=$?
-		if [ $rv -ne 0 ]; then
+		if [[ $rv -ne 0 ]]; then
 			destroy_temp_ipsets
 			die "Error creating ipset '$temp_ipset' with hashsize '$ipset_hash' and maxelements '$ipset_maxelem'."
 		fi
@@ -225,14 +254,14 @@ if [ "$action" = "add" ]; then
 
 		awk -v P="add \"$temp_ipset\"" '{ print P " " $0 }' "$iplist_file" | ipset restore -exist; rv=$?
 
-		if [ $rv -ne 0 ]; then
+		if [[ $rv -ne 0 ]]; then
 			destroy_temp_ipsets
 			die 254 "Error when importing the list from '$iplist_file' into ipset '$temp_ipset'."
 		fi
 
 		echo "Ok."
 
-		[ "$debugmode" ] && ipset_lines_cnt="$(ipset save "$temp_ipset" | grep "add $temp_ipset" | wc -l)"
+		[[ "$debugmode" ]] && ipset_lines_cnt="$(ipset save "$temp_ipset" | grep "add $temp_ipset" | wc -l)"
 		debugprint "subnets in the temporary ipset: $ipset_lines_cnt"
 
 		ipset_hashsizes["$tld"]="$ipset_hash"
@@ -244,11 +273,11 @@ fi
 
 ### Remove existing geoblocker rules for iptables
 
-if [ "$list_type" = "whitelist" ]; then
+if [[ "$list_type" = "whitelist" ]]; then
 	## Temporarily set the policy for the INPUT chain to ACCEPT, in order to prevent user lock out in case of an error
 	echo -n "Setting INPUT chain policy to ACCEPT... "
 	iptables -P INPUT ACCEPT; rv=$?
-	[ $rv -ne 0 ] && die "Error trying to change iptables policy with command 'iptables -P INPUT ACCEPT'."
+	[[ $rv -ne 0 ]] && die "Error trying to change iptables policy with command 'iptables -P INPUT ACCEPT'."
 	echo "Ok."
 	echo
 fi
@@ -261,7 +290,7 @@ for tld in $tlds; do
 	# sed looks for rules with the comment which we use to stamp our rules
 	# sed executes iptables -D (delete) command on matching rules. execution is promtped by the switch /e (only available in GNU sed)
 	iptables-save | sed -r "/INPUT.*comment.*${iptables_comment}/s/-A/iptables -D/e" &>/dev/null; rv="${PIPESTATUS[0]}"
-	if [ $rv -ne 0 ]; then
+	if [[ $rv -ne 0 ]]; then
 		echo "Failed."
 		destroy_temp_ipsets
 		die "Error removing existing rules with command: 'iptables-save | sed -r \"/INPUT.*comment.*$iptables_comment/s/-A/iptables -D/e\" '."
@@ -275,7 +304,7 @@ echo
 ## delete existing iptables rules matching comment "$iptables_comment_global"
 echo -n "Removing existing global iptables rules for '${suite_name}'... "
 iptables-save | sed -r "/INPUT.*comment.*${iptables_comment_global}/s/-A/iptables -D/e" &>/dev/null; rv="${PIPESTATUS[0]}"
-if [ $rv -ne 0 ]; then
+if [[ $rv -ne 0 ]]; then
 	echo "Failed."
 	destroy_temp_ipsets
 	die "Error removing existing rules with command: 'iptables-save | sed -r \"/INPUT.*comment.*${iptables_comment_global}/s/-A/iptables -D/e\" '."
@@ -286,19 +315,19 @@ echo
 
 ### Apply the "remove" action
 
-if [ "$action" = "remove" ]; then
+if [[ "$action" = "remove" ]]; then
 	for tld in $tlds; do
 		perm_ipset="${suite_name}_${tld}"
 
 		# Check if given ipset exists
 		matching_ipset="$(ipset list -n | grep "$perm_ipset")"
-		if [ "$matching_ipset" = "" ]; then
+		if [[ -z "$matching_ipset" ]]; then
 			echo "Warning: Can't remove ipset '$perm_ipset' because it doesn't appear to exist."
 			exitvalue="254"
 		else
 			echo -n "Destroying ipset for country '$tld'... "
 			ipset destroy "$perm_ipset"; rv=$?
-			if [ $rv -ne 0 ]; then
+			if [[ $rv -ne 0 ]]; then
 				echo "Failed."
 				destroy_temp_ipsets
 				die "Error destroying ipset '$perm_ipset'."
@@ -312,13 +341,13 @@ fi
 
 
 # global rules are only used for whitelists. when working with blacklists, don't touch these
-if [ "$list_type" = "whitelist" ]; then
+if [[ "$list_type" = "whitelist" ]]; then
 
 	### Set global iptables rules
 
 	# Add rule to allow connections from the local subnet
 	localsubnet="$(getlocalsubnet)"
-	if [ -z "$localsubnet" ]; then
+	if [[ -z "$localsubnet" ]]; then
 		destroy_temp_ipsets
 		die "Error: couldn't determine local subnet."
 	else
@@ -326,7 +355,7 @@ if [ "$list_type" = "whitelist" ]; then
 		echo -n "Appending rule to allow all traffic from the local subnet... "
 		iptables -A INPUT -s "$localsubnet" -j ACCEPT -m comment --comment "${iptables_comment_global}"; rv=$?
 
-		if [ $rv -ne 0 ]; then
+		if [[ $rv -ne 0 ]]; then
 			destroy_temp_ipsets
 			die "Failed to append rule with command 'iptables -A INPUT -s \"$localsubnet\" -j ACCEPT'."
 		fi
@@ -337,7 +366,7 @@ if [ "$list_type" = "whitelist" ]; then
 	echo -n "Inserting rule to allow all traffic from the loopback interface... "
 	iptables -I INPUT -i lo -j ACCEPT -m comment --comment "${iptables_comment_global}"; rv=$?
 
-	if [ $rv -ne 0 ]; then
+	if [[ $rv -ne 0 ]]; then
 		destroy_temp_ipsets
 		die "Failed to insert rule with command 'iptables -I INPUT -i lo -j ACCEPT'."
 	fi
@@ -347,7 +376,7 @@ if [ "$list_type" = "whitelist" ]; then
 	echo -n "Inserting rule to allow established/related connections... "
 	iptables -I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT -m comment --comment "${iptables_comment_global}"; rv=$?
 
-	if [ $rv -ne 0 ]; then
+	if [[ $rv -ne 0 ]]; then
 		destroy_temp_ipsets
 		die "Failed to insert rules with command 'iptables -I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT'."
 	fi
@@ -358,7 +387,7 @@ fi
 
 
 ### Create permanent ipsets if they don't exist, add iptables rules for them, then swap them with temp ipsets
-if [ "$action" = "add" ]; then
+if [[ "$action" = "add" ]]; then
 	for tld in $tlds; do
 		perm_ipset="${suite_name}_${tld}"
 		temp_ipset="${suite_name}_${tld}_temp"
@@ -370,14 +399,14 @@ if [ "$action" = "add" ]; then
 
 		ipset_length=$(ipset -L "$perm_ipset" 2>/dev/null |  wc -l)
 
-		if [ "$ipset_length" -ge "7" ]; then
+		if [[ "$ipset_length" -ge "7" ]]; then
 			perm_ipset_exists="true"
 			debugprint "found existing permanent ipset '$perm_ipset'."
 		else
 			perm_ipset_exists="false"
 		fi
 
-		if [ "$ipset_length" -eq 0 ]; then
+		if [[ "$ipset_length" -eq 0 ]]; then
 			debugprint "Ipset '$perm_ipset' doesn't exist yet."
 			# to avoid being dependent on ipset output staying constant down the road,
 			# still trying to destroy the ipset, just in case, but not checking the return value
@@ -385,11 +414,11 @@ if [ "$action" = "add" ]; then
 		fi
 
 		## if permanent ipset doesn't exist yet, create it
-		if [ ! "$perm_ipset_exists" = "true" ]; then
+		if [[ ! "$perm_ipset_exists" ]]; then
 			# create new permanent ipset
 			debugprint "Creating permanent ipset '$perm_ipset'... "
 			ipset create "$perm_ipset" hash:net family "$family" hashsize "$ipset_hash" maxelem "$ipset_maxelem"; rv=$?
-			if [ $rv -ne 0 ]; then
+			if [[ $rv -ne 0 ]]; then
 				echo "Failed."
 				ipset destroy "$perm_ipset"
 				destroy_temp_ipsets
@@ -401,12 +430,12 @@ if [ "$action" = "add" ]; then
 		## append the iplist rule to the INPUT chain
 
 
-		if [ "$list_type" = "whitelist" ]; then iptables_action="ACCEPT"; else iptables_action="DROP"; fi
+		if [[ "$list_type" = "whitelist" ]]; then iptables_action="ACCEPT"; else iptables_action="DROP"; fi
 
 		echo -n "Appending $list_type rule for country '$tld' to the INPUT chain... "
 		iptables -A INPUT -m set --match-set "$perm_ipset" src -j "$iptables_action" -m comment --comment "$iptables_comment"; rv=$?
 
-		if [ $rv -ne 0 ]; then
+		if [[ $rv -ne 0 ]]; then
 			ipset destroy "$perm_ipset"
 			destroy_temp_ipsets
 			die "Failed to append ipset rules with command: iptables -I INPUT -m set --match-set \"$perm_ipset\" src -j \"$iptables_action\"."
@@ -416,7 +445,7 @@ if [ "$action" = "add" ]; then
 		## swap the new (temporary) ipset with the old (permanent) ipset
 		echo -n "Making the new $list_type ipset for country '$tld' permanent... "
 		ipset swap "$temp_ipset" "$perm_ipset"; rv=$?
-		if [ $rv -ne 0 ]; then
+		if [[ $rv -ne 0 ]]; then
 			destroy_temp_ipsets
 			die "Failed to swap temporary and permanent ipsets."
 		fi
@@ -426,7 +455,7 @@ if [ "$action" = "add" ]; then
 		## destroy the old ipset (now it's called temporary)
 		debugprint "Destroying the temporary ipset for country '$tld'... "
 		ipset destroy "$temp_ipset"; rv=$?
-		[ $rv -ne 0 ] && die "Failed to destroy ipset '$temp_ipset'. Strange........."
+		[[ $rv -ne 0 ]] && die "Failed to destroy ipset '$temp_ipset'. Strange........."
 		debugprint "Ok."
 	done
 fi
@@ -436,15 +465,15 @@ echo
 ### Configure iptables policies
 
 # DROP policies are only used for whitelists
-if [ "$list_type" = "whitelist" ]; then
-	if [ "$nodrop" != "true" ]; then
+if [[ "$list_type" = "whitelist" ]]; then
+	if [[ ! "$nodrop" ]]; then
 		# set policy on INPUT and FORWARD chains to DROP
 		echo -n "Setting default iptables policies for INPUT and FORWARD chains to DROP... "
 		iptables -P INPUT DROP; rv=$?
-		[ $rv -ne 0 ] && die "Failed to change iptables policy with command 'iptables -P INPUT DROP'."
+		[[ $rv -ne 0 ]] && die "Failed to change iptables policy with command 'iptables -P INPUT DROP'."
 
 		iptables -P FORWARD DROP; rv=$?
-		[ $rv -ne 0 ] && die "Failed to change iptables policy with command 'iptables -P FORWARD DROP'."
+		[[ $rv -ne 0 ]] && die "Failed to change iptables policy with command 'iptables -P FORWARD DROP'."
 		echo "Ok."
 	else
 		echo "WARNING: nodrop was requested. Leaving INPUT and FORWARD chains with ACCEPT policies (geoblocking is inactive)."
@@ -453,15 +482,15 @@ else
 	# set policy on INPUT chain to ACCEPT
 	echo -n "Setting default iptables policy for INPUT chains to ACCEPT... "
 	iptables -P INPUT ACCEPT; rv=$?
-	[ $rv -ne 0 ] && die "Failed to change iptables policy with command 'iptables -P INPUT ACCEPT'."
+	[[ $rv -ne 0 ]] && die "Failed to change iptables policy with command 'iptables -P INPUT ACCEPT'."
 
 fi
 
 # This line is to simulate a simple fault and test recovery from backup
 # Activates when running the script with the -t switch
-[ "$test" ] && die "Test test test"
+[[ "$test" ]] && die "Test test test"
 
-echo ""
+echo
 
 debugexitmsg
 
diff --git a/geoblocker-bash-backup b/geoblocker-bash-backup
--- a/geoblocker-bash-backup
+++ b/geoblocker-bash-backup
@@ -15,20 +15,20 @@
 me=$(basename "$0")
 
 # check for root
-[ "$EUID" -ne 0 ] && {
+[[ "$EUID" -ne 0 ]] && {
 	err="Error: $me needs to be run as root."
 	echo "$err" >&2
-	[ ! "$nolog" ] && logger "$err"
+	[[ ! "$nolog" ]] && logger "$err"
 	exit 1
 }
 
 suite_name="geoblocker-bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-[ -n "$script_dir" ] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
-	[ ! "$nolog" ] && logger "$err"; exit 1; }
+[[ -n "$script_dir" ]] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
+	[[ ! "$nolog" ]] && logger "$err"; exit 1; }
 
 source "$script_dir/${suite_name}-common" || { err="$me: Error: Can't source ${suite_name}-common."; echo "$err" >&2; \
-	[ ! "$nolog" ] && logger "$err"; exit 1; }
+	[[ ! "$nolog" ]] && logger "$err"; exit 1; }
 
 # **NOTE** that some functions and variables are sourced from the *common script
 
@@ -84,7 +84,7 @@ while getopts ":dh" opt; do
 done
 shift $((OPTIND -1))
 
-[[ "$*" != "" ]] && {
+[[ -n "$*" ]] && {
 	usage
 	echo "Error in arguments. First unrecognized argument: '$1'." >&2
 	exit 1
@@ -116,7 +116,7 @@ restore_from_file() {
 	esac
 	debugprint "$restoretarget lines number in backup: $line_cnt"
 
-	if [ "$line_cnt" -gt 0 ]; then
+	if [[ "$line_cnt" -gt 0 ]]; then
 		echo -n "Restoring $restoretarget state from backup... "
 
 		case "$restoretarget" in
@@ -127,7 +127,7 @@ restore_from_file() {
 			ipset) sed -n "/create ${suite_name}/,\$p" "$restorefile" 2>&1 | ipset restore; rv="${PIPESTATUS[1]}" ;;
 		esac
 
-		if [ $rv -eq 0 ]; then
+		if [[ $rv -eq 0 ]]; then
 			echo "Success."
 
 			return 0
@@ -144,14 +144,14 @@ restore_from_file() {
 	err2="*** Deactivating geoblocking and removing cron jobs ***"
 
 	# if -t switch wasn't specified at launch then it's not a test
-	if [ ! "$test" ]; then
+	if [[ ! "$test" ]]; then
 		knowngood_failed "$err1" "$err2"
 	else
 		echo "$err1" >&2
 		echo "-t switch was specified, which means we are in test mode. Skipping emergency deactivation." >&2
 		echo "WARNING: RECOVERY TEST FAILED AND GEOBLOCKER IS CURRENTLY INACTIVE" >&2
 
-		if [ "$restoretarget" = "iptables" ]; then
+		if [[ "$restoretarget" = "iptables" ]]; then
 			die -nolog
 		fi
 	fi
@@ -170,7 +170,7 @@ restoreknowngood() {
 	# sed looks for rules with the comment which we use to stamp our rules
 	# sed executes iptables -D (delete) command on matching rules. execution is promtped by the switch /e (only available in GNU sed)
 	iptables-save | sed -r "/INPUT.*comment.*${iptables_comment}/s/-A/iptables -D/e" &>/dev/null; rv=$?
-	if [ $rv -ne 0 ]; then
+	if [[ $rv -ne 0 ]]; then
 		echo "Failed."
 		err1="Error removing existing iptables rules with command: 'iptables-save | sed -r \"/INPUT.*comment.*$iptables_comment/s/-A/iptables -D/e\" '."
 		knowngood_failed "$err1"
@@ -181,7 +181,7 @@ restoreknowngood() {
 	for curr_ipset in $(ipset list -n | grep "$ipset_tag"); do
 		echo -n "Destroying ipset '$curr_ipset'... "
 		ipset destroy "$curr_ipset"; rv=$?
-		if [ $rv -ne 0 ]; then
+		if [[ $rv -ne 0 ]]; then
 			knowngood_failed "Error destroying ipset '$curr_ipset'."
 		else
 			echo "Ok."
@@ -198,7 +198,7 @@ restoreknowngood() {
 knowngood_failed() {
 	echo
 	echolog -err "$1" "$2"
-	if [[ "$emergency_deactivation" != "" ]]; then ${suite_name}-reset; fi
+	if [[ -n "$emergency_deactivation" ]]; then ${suite_name}-reset; fi
 	debugexitmsg
 	exit 1
 }
@@ -223,16 +223,16 @@ knowngood_file="$datadir/iptables_knowngood.bak"
 missing_deps="$(check_deps iptables-save iptables-restore ipset)" || die "Error: missing dependencies: $missing_deps."
 
 # check that the config file exists
-[ ! -f "$conf_file" ] && die "Config file '$conf_file' doesn't exist! Run the installation script again."
+[[ ! -f "$conf_file" ]] && die "Config file '$conf_file' doesn't exist! Run the installation script again."
 
 # check for knowngood file path
-if [ -z "$knowngood_file" ]; then
+if [[ -z "$knowngood_file" ]]; then
 	die "Error: Could not read the backup file path from config."
 fi
 
 # check for valid action
 
-[ -z "$action" ] && { usage; die "Specify action!"; }
+[[ -z "$action" ]] && { usage; die "Specify action!"; }
 
 case "$action" in
 	create-backup) ;;
@@ -243,14 +243,14 @@ esac
 
 #### MAIN
 
-if [ "$action" = "create-backup" ]; then
+if [[ "$action" = "create-backup" ]]; then
 ### Create backup file for known-good iptables state and save current state to the file
 
 	echo -n "Creating backup of current iptables state... "
 	touch "${knowngood_file}.new"
 
 	iptables-save > "${knowngood_file}.new"; rv=$?
-	[ "$rv" -ne 0 ] && die "Error creating backup of iptables state with command: 'iptables-save > ${knowngood_file}.new'."
+	[[ "$rv" -ne 0 ]] && die "Error creating backup of iptables state with command: 'iptables-save > ${knowngood_file}.new'."
 	echo "Ok."
 
 		# we use the same file for iptables and ipset backup
@@ -264,27 +264,27 @@ if [ "$action" = "create-backup" ]; then
 		curr_ipset="${suite_name}_${curr_tld}"
 		echo -n "Creating backup of ipset '$curr_ipset'... "
 		ipset save "$curr_ipset" >> "${knowngood_file}.new"; rv=$?
-		[ "$rv" -ne 0 ] && die "Error creating backup of ipset '$curr_ipset'."
+		[[ "$rv" -ne 0 ]] && die "Error creating backup of ipset '$curr_ipset'."
 	echo "Ok."
 	done
 
 	cp "$conf_file" "$conf_file_backup"; rv=$?
-	[ "$rv" -ne 0 ] && die "Error creating a backup copy of the config file."
+	[[ "$rv" -ne 0 ]] && die "Error creating a backup copy of the config file."
 
 	mv "$knowngood_file.new" "$knowngood_file"; rv=$?
-	[ "$rv" -ne 0 ] && die "Error overwriting the backup file."
+	[[ "$rv" -ne 0 ]] && die "Error overwriting the backup file."
 
 	echo -e "\nSuccessfully created backup of config, ipsets and iptables rules."
 	echo "Backup file: '$knowngood_file'"
 fi
 
-if [ "$action" = "restore" ]; then
+if [[ "$action" = "restore" ]]; then
 ### Restore iptables and ipsets to known-good state from backup file
 	restoreknowngood "$knowngood_file"
 	echolog "Successfully restored known-good ipset and iptables state from backup."
 	echo
 	cp "$conf_file_backup" "$conf_file"; rv=$?
-	[ "$rv" -ne 0 ] && die "Error restoring the config file from backup."
+	[[ "$rv" -ne 0 ]] && die "Error restoring the config file from backup."
 fi
 
 debugexitmsg
diff --git a/geoblocker-bash-common b/geoblocker-bash-common
--- a/geoblocker-bash-common
+++ b/geoblocker-bash-common
@@ -8,40 +8,52 @@
 ### Functions
 
 check_deps(){
-# tests commands specified in arguments
+# tests commands specified in arguments and complains if something's missing (by echo'ing it out in the end and setting return value to 1)
 # if an argument contains '|' then tests for all alternatives and only if all are missing, complains
+
+	# check for bash >= 4.3
+	bash_v="${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}"
+	requiredver="4.3"
+	if [ "$(printf '%s\n' "$requiredver" "$bash_v" | sort -V | head -n1)" != "$requiredver" ]; then
+		echo "Error: missing dependency: 'bash v${requiredver}' or higher is required but 'bash v$bash_v' is installed." >&2
+		echo
+		exit 1
+	fi
 
 	local missing_deps=""
 	local err=0
 
 	# implicitly loops over arguments
 	for dep; do
+		# process 'or' statements received as 'command_1|command_2...|command_n'
 		if [[ "$dep" = *'|'* ]]; then
-			dep_alt="${dep//'|'/' '}"
 			local test_alt_cnt=0
 			local err_alt_cnt=0
 			local alt_dep_list=""
 
+			# replace '|' delimiter with ' ' delimiter
+			dep_alt="${dep//'|'/' '}"
+			# process all space-delimited alternatives
 			for dep in $dep_alt; do
 				let test_alt_cnt++
 				! command -v "$dep" &> /dev/null && let err_alt_cnt++
-				[ -z "$alt_dep_list" ] && alt_dep_list="'$dep'" || alt_dep_list="$alt_dep_list or '$dep'"
+				[[ -z "$alt_dep_list" ]] && alt_dep_list="'$dep'" || alt_dep_list="$alt_dep_list or '$dep'"
 			done
 
-			if [ "$err_alt_cnt" -ge "$test_alt_cnt" ]; then
-				[ -z "$missing_deps" ] && missing_deps="$alt_dep_list" || missing_deps="${missing_deps}, $alt_dep_list"
+			if [[ "$err_alt_cnt" -ge "$test_alt_cnt" ]]; then
+				[[ -z "$missing_deps" ]] && missing_deps="$alt_dep_list" || missing_deps="${missing_deps}, $alt_dep_list"
 				let err++
 			fi
 
 		else
 			if ! command -v "$dep" &> /dev/null; then
-				[ -z "$missing_deps" ] && missing_deps="'$dep'" || missing_deps="${missing_deps}, '$dep'"
+				[[ -z "$missing_deps" ]] && missing_deps="'$dep'" || missing_deps="${missing_deps}, '$dep'"
 				let err++
 			fi
 		fi
 	done
 
-	[ "$err" -gt 0 ] && { echo "$missing_deps"; return 1; } || return 0
+	[[ "$err" -gt 0 ]] && { echo "$missing_deps"; return 1; } || return 0
 }
 
 echolog() {
@@ -50,30 +62,30 @@ echolog() {
 	msg_args1=()
 	# check for "-err" option in arguments
 	for msg_arg in "$@"; do
-		[ "$msg_arg" = "-err" ] && msg_is_err="true" || msg_args1+=( "$msg_arg" )
+		[[ "$msg_arg" = "-err" ]] && msg_is_err="true" || msg_args1+=( "$msg_arg" )
 	done
 
 	msg_args2=()
 	# check for "-noecho" option in arguments
 	for msg_arg in "${msg_args1[@]}"; do
-		[ "$msg_arg" = "-noecho" ] && noecho="true" || msg_args2+=( "$msg_arg" )
+		[[ "$msg_arg" = "-noecho" ]] && noecho="true" || msg_args2+=( "$msg_arg" )
 	done
 
-	if [ -n "${msg_args2[*]}" ]; then
+	if [[ -n "${msg_args2[*]}" ]]; then
 		# loop through arguments and print them to stderr and to the syslog
 		# "$nolog" is set as environment variable (used in *manage and *install scripts)
 		for arg in "${msg_args2[@]}"; do
-			if [ "$noecho" != "true" ]; then
-				[ "$msg_is_err" ] && echo "$me_short: $arg" 1>&2 || echo "$me_short: $arg"
+			if [[ ! "$noecho" ]]; then
+				[[ "$msg_is_err" ]] && echo "$me_short: $arg" 1>&2 || echo "$me_short: $arg"
 			fi
-			[ "$nolog" != "true" ] && logger -t "$me" "$arg"
+			[[ ! "$nolog" ]] && logger -t "$me" "$arg"
 		done
 	fi
 }
 
 debugprint() {
 # prints a debug message
-	[ "$debugmode" ] && echo -e "	Debug: ${me_short}: $*" >&2
+	[[ "$debugmode" ]] && echo -e "	Debug: ${me_short}: $*" >&2
 }
 
 debugentermsg() {
@@ -82,7 +94,7 @@ debugentermsg() {
 }
 
 debugexitmsg() {
-	[ -n "$parent_short_cap" ] && debugprint "\033[1;33mBack to *$parent_short_cap*...\033[0m"
+	[[ -n "$parent_short_cap" ]] && debugprint "\033[1;33mBack to *$parent_short_cap*...\033[0m"
 }
 
 die() {
@@ -93,19 +105,19 @@ die() {
 
 	# check for "-nolog" option in arguments
 	for die_arg in "$@"; do
-		[ "$die_arg" = "-nolog" ] && nolog="true" || die_args+=( "$die_arg" )
+		[[ "$die_arg" = "-nolog" ]] && nolog="true" || die_args+=( "$die_arg" )
 	done
 
-	if [ -n "${die_args[*]}" ]; then
+	if [[ -n "${die_args[*]}" ]]; then
 		echo >&2
 		# loop through arguments and print them to stderr and to the syslog
 		# "$nolog" is set either when calling die() or as environment variable (used in *manage and *install scripts)
 		for arg in "${die_args[@]}"; do
 			echo "$me_short: $arg" >&2
-			[ "$nolog" != "true" ] && logger -t "$me" "$arg"
+			[[ ! "$nolog" ]] && logger -t "$me" "$arg"
 		done
 	fi
-	[ -n "$parent_short_cap" ] && debugprint "\033[1;33mBack to $parent_short_cap...\033[0m"
+	[[ -n "$parent_short_cap" ]] && debugprint "\033[1;33mBack to $parent_short_cap...\033[0m"
 	echo >&2
 	exit "$rv"
 }
@@ -116,7 +128,7 @@ getconfig() {
 # returns 0 if successful
 	key_conf="$1"
 	target_file="${2:-$conf_file}"
-	[ -z "$key_conf" ] || [ -z "$target_file" ] && return 1
+	[[ -z "$key_conf" || -z "$target_file" ]] && return 1
 
 	entry="$(grep "$key_conf=" "$target_file" 2>/dev/null)" || return 2
 
@@ -132,7 +144,8 @@ getstatus() {
 # rest of the arguments are passed as is to setconfig()
 	target_file="$1"
 	shift 1
-	[ -n "$target_file" ] && { status_value="$(getconfig "$*" "$target_file")"; rv=$?; } || rv=1
+	local rv=0
+	[[ -n "$target_file" ]] && { status_value="$(getconfig "$*" "$target_file")"; rv=$?; } || rv=1
 	printf "%s" "$status_value"
 	return $rv
 }
@@ -142,6 +155,7 @@ setconfig() {
 # if one of the value pairs is "target_file=[file]" then writes to $file instead
 # returns 0 if successful, 1 if not
 
+# uncomment for debug
 #	local arguments=("$@")
 #	local args="$(for arg in "${arguments[@]}"; do printf "%s" "'$arg' "; done)"
 #	debugprint "\033[1;33mStarted *setconfig* with args: ${args}\033[0m"
@@ -151,7 +165,7 @@ setconfig() {
 
 	# loop through arguments
 	for argument_conf in "$@"; do
-		# in case an argument contains multiple lines, we read each line into a separate lines_arr element
+		# read each line into a separate lines_arr element (needed in case an argument contains multiple lines)
 		readarray -t lines_arr <<< "$argument_conf"
 		for line in "${lines_arr[@]}"; do
 			# only process the line if it contains '='
@@ -159,10 +173,10 @@ setconfig() {
 		   		key_conf="$(cut -f1 -d= <<< "$line")"
 		   		key_length=${#key_conf}
 		   		value_conf="${line:$key_length+1}"
-		   		if [ "$key_conf" = "target_file" ]; then
+		   		if [[ "$key_conf" = "target_file" ]]; then
 					arguments_target_file="$value_conf"
 				else
-					[ -n "$key_conf" ] && arguments_arr["$key_conf"]="$(awk '{$1=$1};1' <<< "$value_conf")"
+					[[ -n "$key_conf" ]] && arguments_arr["$key_conf"]="$(awk '{$1=$1};1' <<< "$value_conf")"
 				fi
 			fi
 		done
@@ -171,10 +185,10 @@ setconfig() {
 	target_file="${arguments_target_file:-$conf_file}"
 
 	# Check that $target_file variable is not empty
-	[[ "$target_file" = "" ]] && { die "*common: setconfig: '\$target_file' variable is not set!"; }
+	[[ -z "$target_file" ]] && { die "*common: setconfig: '\$target_file' variable is not set!"; }
 
 	# create the config file if it doesn't exist
-	if [ ! -f "$target_file" ]; then
+	if [[ ! -f "$target_file" ]]; then
 		touch "$target_file" || { die "*common: setconfig: could not create target_file '$target_file'"; }
 	fi
 
@@ -204,7 +218,8 @@ setstatus() {
 # rest of the arguments are passed as is to setconfig()
 	target_file="$1"
 	shift 1
-	[ -n "$target_file" ] && { setconfig "target_file=$target_file" "${@}"; rv=$?; } || rv=1
+	local rv=0
+	[[ -n "$target_file" ]] && { setconfig "target_file=$target_file" "${@}"; rv=$?; } || rv=1
 	return $rv
 }
 
@@ -290,7 +305,7 @@ check_tlds_coherency() {
 	missing_tlds="$(subtract_list_a_from_b "$active_tlds" "$config_tlds")"
 	tlds_difference="$(find_lists_difference "$active_tlds" "$config_tlds")"
 
-	if [ "$tlds_difference" = "" ]; then
+	if [[ -z "$tlds_difference" ]]; then
 		debugprint "Successfully verified config coherency."
 		return 0
 	else
@@ -317,13 +332,13 @@ find_active_tlds() {
 	tlds_difference="$(find_lists_difference "$current_ipset_tlds" "$current_iprules_tlds")"
 	tlds_merged="$(merge_lists "$current_ipset_tlds" "$current_iprules_tlds")"
 
-	if [ "$1" = "all" ]; then
+	if [[ "$1" = "all" ]]; then
 		printf "%s" "$tlds_merged"
 	else
 		printf "%s" "$tlds_intersection"
 	fi
 
-	[ "$tlds_difference" == "" ] && return 0 || { ipsets_incoherent="true"; return 1; }
+	[[ -z "$tlds_difference" ]] && return 0 || { ipsets_incoherent="true"; return 1; }
 }
 
 
@@ -341,35 +356,6 @@ find_active_tlds() {
 #	echo "$DIR"
 #}
 
-getlocalsubnet() {
-# attempts to find local subnet for the main network interface
-
-	# regex patterns used for ipv4 validation
-	# using Perl regex syntax because grep is faster with it than with native grep syntax
-	# regex compiled from 2 suggestions found here:
-	# https://stackoverflow.com/questions/5284147/validating-ipv4-addresses-with-regexp
-	ip_regex='^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}'
-	mask_regex='(/([01]?\d\d?|2[0-4]\d|25[0-5]))$'
-	subnet_regex="${ip_regex}${mask_regex}"
-
-	# returns local ip with subnet mask
-	localip="$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}')"
-
-	# Change last ipv4 octet to 0
-	lsubnet="$(printf "%s" "$localip" | sed 's|\([0-9]*\.[0-9]*\.[0-9]*\.\)[0-9]*|\10|')"
-
-	# Verifies that the argument is a valid ipv4 subnet
-	printf "%s" "$lsubnet" | grep -P "$subnet_regex" &>/dev/null; rv=$?
-
-	if [ $rv -ne 0 ]; then
-		# if validation fails, output empty string
-		printf "%s" ""
-	else
-		printf "%s" "$lsubnet"
-	fi
-	return $rv
-}
-
 sanitize_args() {
 # trims extra whitespaces, discards empty arguments
 arguments=()
@@ -377,7 +363,7 @@ for arg in "$@"; do
 	# trim leading and trailing whitespaces
 	arg="$(awk '{$1=$1};1' <<< "$arg")"
 	# add to array while discarding empty arguments
-	[ -n "$arg" ] && arguments+=("$arg")
+	[[ -n "$arg" ]] && arguments+=("$arg")
 done
 }
 
@@ -401,7 +387,7 @@ me_short_cap="${me_short^^}"
 
 parent="$(basename "$(ps -o args= $PPID)" 2>/dev/null | awk -v RS='/| ' '/^.*'$suite_name'/ {a=$0} END{print a}')"
 
-[ "$parent" = "$me" ] && parent=""
+[ "$parent" = "$me" ]] && parent=""
 parent_short="${parent//"${suite_name}-"/}"
 parent_short_cap="${parent_short^^}"
 
diff --git a/geoblocker-bash-cronsetup b/geoblocker-bash-cronsetup
--- a/geoblocker-bash-cronsetup
+++ b/geoblocker-bash-cronsetup
@@ -10,7 +10,7 @@
 me=$(basename "$0")
 
 # check for root
-[ "$EUID" -ne 0 ] && {
+[[ "$EUID" -ne 0 ]] && {
 	err="Error: $me needs to be run as root."
 	echo "$err" >&2
 	exit 1
@@ -18,7 +18,7 @@ me=$(basename "$0")
 
 suite_name="geoblocker-bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-[ -n "$script_dir" ] && cd "$script_dir" || { echo "$me: Error: Couldn't cd into '$script_dir'." >&2; exit 1; }
+[[ -n "$script_dir" ]] && cd "$script_dir" || { echo "$me: Error: Couldn't cd into '$script_dir'." >&2; exit 1; }
 
 source "$script_dir/${suite_name}-common" || { echo "$me: Error: Can't source ${suite_name}-common." >&2; exit 1; }
 
@@ -52,7 +52,7 @@ while getopts ":dh" opt; do
 done
 shift $((OPTIND -1))
 
-[[ "$*" != "" ]] && {
+[[ -n "$*" ]] && {
 	usage
 	echo "Error in arguments. First unrecognized argument: '$1'." >&2
 	echo "Note: When specifying cron schedule, put it in double braces." >&2
@@ -78,7 +78,7 @@ create_cron_job() {
 	# check that countries list in config is not empty
 	config_tlds="$(getconfig "Countries")" || { die -nolog "Error: Couldn't read value for Countries from the config file."; }
 
-	if [ -z "$config_tlds" ]; then
+	if [[ -z "$config_tlds" ]]; then
 		die -nolog "Error: Countries list in the config file is empty! No point in creating autoupdate job."
 	fi
 
@@ -86,11 +86,11 @@ create_cron_job() {
 
 		autoupdate)
 
-			[ -z "$cron_schedule" ] && die -nolog "Error: cron schedule in the config file is empty!"
+			[[ -z "$cron_schedule" ]] && die -nolog "Error: cron schedule in the config file is empty!"
 			# Validate cron schedule
 			debugprint "Validating cron schedule: '$cron_schedule'."
 			validate-cron-schedule.sh -x "$cron_schedule"; rv=$?
-			if [ "$rv" -ne 0 ]; then
+			if [[ "$rv" -ne 0 ]]; then
 				die -nolog "Error validating cron schedule '$cron_schedule'."
 			else
 				debugprint "Successfully validated cron schedule: '$cron_schedule'."
@@ -121,7 +121,7 @@ create_cron_job() {
 	echo -e "$(sudo crontab -u root -l 2>/dev/null)\n$cron_command" | sudo crontab -u root -
 	rv=$?
 
-	if [ $rv -ne 0 ]; then
+	if [[ $rv -ne 0 ]]; then
 		die -nolog "Error creating $job_type cron job!"
 	else
 		debugprint "Ok."
@@ -136,7 +136,7 @@ remove_cron_job() {
 
 	job_type="$1"
 
-	if [ -n "$job_type" ] ; then
+	if [[ -n "$job_type" ]] ; then
 		if [[ "$job_type" != "autoupdate" && "$job_type" != "persistence" ]]; then
 				die -nolog "Error: unknown cron job type '$job_type'."
 		fi
@@ -145,7 +145,7 @@ remove_cron_job() {
 		crontab -u root -l 2>/dev/null | grep -v "${suite_name}-${job_type}" | sudo crontab -u root -
 		rv=$?
 
-		if [ $rv -ne 0 ]; then
+		if [[ $rv -ne 0 ]]; then
 			die -nolog "Error: failed to remove $job_type cron job."
 		else
 			debugprint "Ok."
@@ -182,33 +182,33 @@ sleeptime="$(getconfig "RebootSleep")" || { die -nolog "Error: Couldn't read val
 #### Main
 
 echo -n "Updating crontab..."
-[ "$debugmode" ] && echo
+[[ "$debugmode" ]] && echo
 
 ### remove the persistence cron job before any other action since this will be done anyway
 remove_cron_job "persistence"
 
 # only remove the autoupdate cron job now if we know that autoupdate should be disabled
-if [ "$cron_schedule" = "disable" ]; then
+if [[ "$cron_schedule" = "disable" ]]; then
 	remove_cron_job "autoupdate"
 fi
 
 ### create new persistence cron job
-if [[ "$no_persistence" != "true" ]]; then
+if [[ ! "$no_persistence" ]]; then
 	create_cron_job "persistence"
 fi
 
 ### create new autoupdate cron job
-if [ "$cron_schedule" != "disable" ]; then
+if [[ "$cron_schedule" != "disable" ]]; then
 	create_cron_job "autoupdate"
 fi
 
 cron_lines="$(crontab -u root -l 2>/dev/null | grep "${suite_name}")"
-[ "$debugmode" ] && echo
+[[ "$debugmode" ]] && echo
 debugprint "Updated crontab: \n$cron_lines\n"
 
 echo "Ok."
 
-if [[ "$no_persistence" = "true" ]]; then
+if [[ "$no_persistence" ]]; then
 	echo
 	echo "Note: no persistence was configured during installation. Geoblocking will be deactivated upon reboot!"
 	echo "To enable persistence, run the *install script again without the '-n' option."
diff --git a/geoblocker-bash-fetch b/geoblocker-bash-fetch
--- a/geoblocker-bash-fetch
+++ b/geoblocker-bash-fetch
@@ -21,11 +21,11 @@ me=$(basename "$0")
 
 suite_name="geoblocker-bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-[ -n "$script_dir" ] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
-	[ ! "$nolog" ] && logger "$err"; exit 1; }
+[[ -n "$script_dir" ]] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
+	[[ ! "$nolog" ]] && logger "$err"; exit 1; }
 
 source "$script_dir/${suite_name}-common" || { err="$me: Error: Can't source ${suite_name}-common."; echo "$err" >&2; \
-	[ ! "$nolog" ] && logger "$err"; exit 1; }
+	[[ ! "$nolog" ]] && logger "$err"; exit 1; }
 
 # **NOTE** that some functions and variables are sourced from the *common script
 
@@ -81,7 +81,7 @@ while getopts ":c:p:s:o:fdh" opt; do
 done
 shift $((OPTIND -1))
 
-[[ "$*" != "" ]] && {
+[[ -n "$*" ]] && {
 	usage
 	err1="Error in arguments. First unrecognized argument: '$1'."
 	err2="Note: If specifying multiple country codes, put them between double quotation marks."
@@ -122,7 +122,7 @@ parse_arin() {
 		tr -d " " > "$parsed_file"
 
 	# check that $parsed_file is non-empty
-	[ -s "$parsed_file" ] && rv=0 || rv=1
+	[[ -s "$parsed_file" ]] && rv=0 || rv=1
 	return "$rv"
 }
 
@@ -219,7 +219,7 @@ command -v "wget" &> /dev/null && wget_exists="true"
 
 tlds_cnt="$(wc -l <<< "$tlds")"
 
-[ "$tlds_cnt" -eq 0 ] && { usage; die "Specify country code/s!"; }
+[[ "$tlds_cnt" -eq 0 ]] && { usage; die "Specify country code/s!"; }
 
 # check that either $iplist_dir or $output_file is set
 [[ -z "$iplist_dir" && -z "$output_file" ]] && { usage; die "Specify iplist directory with '-p <path-to-dir>' or output file with '-o <output_file>'."; }
@@ -257,9 +257,9 @@ for tld in $tlds; do
 	list_path="${output_file:-$iplist_dir/$filename}"
 	fetched_file=$(mktemp "/tmp/fetched-$tld-XXXX")
 
-	if [ "$wget_exists" ]; then
+	if [[ "$wget_exists" ]]; then
 		fetch_command="$wget_command $url -O"
-	elif [ "$curl_exists" ]; then
+	elif [[ "$curl_exists" ]]; then
 		fetch_command="$curl_command $url -o"
 	fi
 
@@ -297,7 +297,7 @@ for tld in $tlds; do
 			rm "$fetched_file" &>/dev/null
 			tld_status="failed"
 			echolog "Error when running '$fetch_command'."
-			[ "$retry_cnt" -ge "$fetch_retries" ] && break
+			[[ "$retry_cnt" -ge "$fetch_retries" ]] && break
 		else
 			echo "Fetch successful."
 
@@ -307,8 +307,8 @@ for tld in $tlds; do
 
 			# skip list update if data timestamp didn't change, and there were no validation errors in the old list,
 			# and we are not in manual mode, and force_update wasn't requested
-			if [[ "$old_list_exists" &&  "$date_new" -le "$date_old" && "$force_update" != "true" && \
-							"$manualmode" != "true" && "$old_failed_subnets_cnt" -eq 0 ]]; then
+			if [[ "$old_list_exists" &&  "$date_new" -le "$date_old" && ! "$force_update" && \
+							! "$manualmode" && "$old_failed_subnets_cnt" -eq 0 ]]; then
 				echolog "Subnets list for country '$tld' is already up-to-date. Timestamp: '$(date --date=@$date_new)'."
 				tld_status="up_to_date"
 				rm "$fetched_file" &>/dev/null
@@ -326,11 +326,11 @@ for tld in $tlds; do
 			esac
 			rm "$fetched_file" &>/dev/null
 
-			if [ "$rv" -ne 0 ]; then
+			if [[ "$rv" -ne 0 ]]; then
 				rm "$parsed_file" &>/dev/null
 				tld_status="failed"
 				echo -e "\nError: failed to parse the fetched file for country '$tld'." >&2
-				[ "$retry_cnt" -ge "$fetch_retries" ] && break
+				[[ "$retry_cnt" -ge "$fetch_retries" ]] && break
 			else
 				echo "Ok."
 				# Validate the parsed file
@@ -344,9 +344,9 @@ for tld in $tlds; do
 				validated_subnets_cnt=$(wc -l < "$validated_file")
 
 				failed_subnets_cnt=$(( parsed_subnets_cnt - validated_subnets_cnt ))
-				if [ "$failed_subnets_cnt" -gt 0 ]; then
+				if [[ "$failed_subnets_cnt" -gt 0 ]]; then
 					echolog -err "Note: Fetch attempt $retry_cnt for country '$tld': $failed_subnets_cnt subnets failed validation."
-					[ "$retry_cnt" -ge "$fetch_retries" ] && { tld_status="partial"; break; }
+					[[ "$retry_cnt" -ge "$fetch_retries" ]] && { tld_status="partial"; break; }
 					rm "$validated_file" &>/dev/null
 				else
 					echo "Ok."
@@ -358,7 +358,7 @@ for tld in $tlds; do
 		echo -e "Retrying fetch for country '$tld'...\n"
 	done
 
-	if [[ "$tld_status" = "Ok" || "$tld_status" = "partial" ]] && [ "$validated_subnets_cnt" -eq 0 ]; then
+	if [[ "$tld_status" = "Ok" || "$tld_status" = "partial" ]] && [[ "$validated_subnets_cnt" -eq 0 ]]; then
 		rm "$validated_file" &>/dev/null
 		echolog "Error: validated 0 subnets for country '$tld'. Perhaps the country code is incorrect?" >&2
 		tld_status="failed"
@@ -370,7 +370,7 @@ for tld in $tlds; do
 	if [[ "$old_list_exists" && "$tld_status" != "up_to_date" ]]; then
 		# compare fetched subnets count to old subnets count, get result in %
 		subnets_percents="$(echo "scale=0 ; $validated_subnets_cnt * 100 / $old_subnets_cnt" | bc)"
-		if [ "$subnets_percents" -lt 90 ]; then
+		if [[ "$subnets_percents" -lt 90 ]]; then
 			tld_status="failed"
 			rm "$validated_file" &>/dev/null
 			echolog -err "Warning: validated subnets count '$validated_subnets_cnt' in the fetched list for country '$tld'..."
@@ -382,13 +382,13 @@ for tld in $tlds; do
 	fi
 
 	# If we have a partial list, decide whether to consider it Ok or not
-	if [ "$tld_status" = "partial" ]; then
+	if [[ "$tld_status" = "partial" ]]; then
 			echolog -err "Warning: out of $parsed_subnets_cnt, $failed_subnets_cnt subnets for country '$tld' failed validation."
 			echolog -err "Invalid subnets removed from the list."
 
-		if [ "$old_list_exists" = "true" ]; then
+		if [[ "$old_list_exists" ]]; then
 			## don't update the list if it is partial and the count of failed validations increased compared to the old list
-			if [ "$failed_subnets_cnt" -gt "$old_failed_subnets_cnt" ]; then
+			if [[ "$failed_subnets_cnt" -gt "$old_failed_subnets_cnt" ]]; then
 				rm "$validated_file" &>/dev/null
 				tld_status="failed"
 				err1="Warning: failed subnets count '$failed_subnets_cnt' for country '$tld' is higher than '$old_failed_subnets_cnt' in the old list."
@@ -400,7 +400,7 @@ for tld in $tlds; do
 		else
 			# old list does not exist
 			# if we are in manual mode, meaning we were launched from either the *install or the *manage script
-			if [ "$manualmode" = "true" ]; then
+			if [[ "$manualmode" ]]; then
 				# if an older existing list is unavailable, ask the user what to do
 				echo -e "\n\nWarning: Ip list for country '$tld' has been fetched but may be incomplete, and there is no older downloaded file for this list."
 				echo "Use the incomplete list anyway?"
@@ -419,7 +419,7 @@ for tld in $tlds; do
 
 	echo
 
-	if [ "$tld_status" = "Ok" ]; then
+	if [[ "$tld_status" = "Ok" ]]; then
 		echo -e "Validated subnets count for country '$tld': $validated_subnets_cnt.\n"
 	fi
 
@@ -432,11 +432,11 @@ for tld in $tlds; do
 		* ) echolog -err "Error: validation status for country '$tld' is '$tld_status' which I don't understand. This should not happen. Please file a bug report." ;;
 	esac
 
-	if [ "$tld_status" = "Ok" ]; then
+	if [[ "$tld_status" = "Ok" ]]; then
 
 		echo -n "Updating $list_path... "
 		mv "$validated_file" "$list_path"; rv=$?
-		if [ $rv -ne 0 ]; then
+		if [[ $rv -ne 0 ]]; then
 			echo "Failed."
 			rm "$validated_file" &>/dev/null
 			echolog -err "Failed to overwrite the file '$list_path'"
@@ -450,7 +450,7 @@ for tld in $tlds; do
 
 	fi
 
-	if [ "$tld_status" = "up_to_date" ]; then
+	if [[ "$tld_status" = "up_to_date" ]]; then
 		up_to_date_tlds="$up_to_date_tlds $tld"
 		failed_subnets_cnt_arr["$tld"]="$failed_subnets_cnt"
 	fi
@@ -459,7 +459,7 @@ for tld in $tlds; do
 done
 
 # report fetch results back to caller via status file
-if [ -n "$status_file" ]; then
+if [[ -n "$status_file" ]]; then
 	# convert array contents to formatted string for writing to the status file
 	for tld in "${!failed_subnets_cnt_arr[@]}"; do
 
diff --git a/geoblocker-bash-install b/geoblocker-bash-install
--- a/geoblocker-bash-install
+++ b/geoblocker-bash-install
@@ -16,7 +16,7 @@
 me=$(basename "$0")
 
 # check for root
-[ "$EUID" -ne 0 ] && {
+[[ "$EUID" -ne 0 ]] && {
 	err="Error: $me needs to be run as root."
 	echo "$err" >&2
 	exit 1
@@ -24,7 +24,7 @@ me=$(basename "$0")
 
 suite_name="geoblocker-bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-[ -n "$script_dir" ] && cd "$script_dir" || { echo "$me: Error: Couldn't cd into '$script_dir'." >&2; exit 1; }
+[[ -n "$script_dir" ]] && cd "$script_dir" || { echo "$me: Error: Couldn't cd into '$script_dir'." >&2; exit 1; }
 
 source "$script_dir/${suite_name}-common" || { echo "$me: Error: Can't source '${suite_name}-common'." >&2; exit 1; }
 
@@ -101,7 +101,7 @@ while getopts ":c:m:s:enpdh" opt; do
 done
 shift $((OPTIND -1))
 
-[[ "$*" != "" ]] && {
+[[ -n "$*" ]] && {
 	usage
 	err1="Error in arguments. First unrecognized argument: '$1'."
 	err2="Note: If specifying multiple country codes, put them in double quotation marks."
@@ -128,12 +128,12 @@ check_files_exist() {
 	# implicitly loops over arguments
 	for dep_file; do
 
-		if [ ! -s "$dep_file" ]; then
-			[ -z "$missing_files" ] && missing_files="'$dep_file'" || missing_deps="${missing_files}, '$dep_file'"
+		if [[ ! -s "$dep_file" ]]; then
+			[[ -z "$missing_files" ]] && missing_files="'$dep_file'" || missing_deps="${missing_files}, '$dep_file'"
 			let err++
 		fi
 	done
-	[ "$err" -gt 0 ] && { echo "$missing_files"; return 1; } || return 0
+	[[ "$err" -gt 0 ]] && { echo "$missing_files"; return 1; } || return 0
 }
 
 copyscripts() {
@@ -179,7 +179,7 @@ default_schedule="0 4 * * *"
 cron_schedule="${cron_schedule:-$default_schedule}"
 sleeptime="30"
 
-if [ -n "$list_type" ]; then
+if [[ -n "$list_type" ]]; then
 	# convert to lower case
 	list_type="${list_type,,}"
 
@@ -190,16 +190,16 @@ fi
 #### CHECKS
 
 # check for systemd
-[ "$(! ps -p 1 -o comm=)" != "systemd" ] && die "Error: systemd is required but this sytem does not appear to be running systemd."
+[[ "$(! ps -p 1 -o comm=)" != "systemd" ]] && die "Error: systemd is required but this sytem does not appear to be running systemd."
 
 missing_deps="$(check_deps "curl|wget" jq iptables-save iptables-restore ipset)" || die "Error: missing dependencies: $missing_deps."
 
-if [ -z "$tlds" ]; then
+if [[ -z "$tlds" ]]; then
 	usage
 	die "Specify countries with '-c <tlds>'!"
 fi
 
-if [ -z "$list_type" ]; then
+if [[ -z "$list_type" ]]; then
 	usage
 	die "Specify firewall mode with '-m whitelist' or '-m blacklist'!"
 fi
@@ -224,7 +224,7 @@ setconfig "Countries=" "ListType=$list_type" "Installdir=$install_dir" "Datadir=
 	"RebootSleep=$sleeptime" "Backup_script=$backup_script" "EmergencyDeactivation=$emergency_deactivation" \
 	"NoPersistence=$no_persistence" "NoDrop=$nodrop"; rv=$?
 
-if [ "$rv" -ne 0 ]; then
+if [[ "$rv" -ne 0 ]]; then
 	echo "Failed." >&2
 	install_failed "Error writing initial config to the config file."
 else echo "Ok."
@@ -239,11 +239,11 @@ mkdir -p "$iplist_dir"
 echo -n "Creating file for backup of iptables state..."
 
 # if a backup file already exists, continue installing but skip overwriting the backup file
-if [ -f "$knowngood_file" ]; then
+if [[ -f "$knowngood_file" ]]; then
 	echo "Backup file already exists, skipping."
 else
 	touch "$knowngood_file"; rv=$?
-	if [ $rv -ne 0 ]; then
+	if [[ $rv -ne 0 ]]; then
 		echo "Error." >&2
 		install_failed
 	fi
@@ -258,7 +258,7 @@ bash ${suite_name}-reset
 ## Copy scripts to $install_dir
 
 # if we are running from $install_dir, assume that all other necessary scripts have already been installed, skip copying
-if [ "$script_dir" != "$install_dir" ]; then
+if [[ "$script_dir" != "$install_dir" ]]; then
 	echo -n "Copying scripts to $install_dir... "
 	copyscripts "${suite_name}-common" "${suite_name}-fetch" "${suite_name}-apply" "${suite_name}-run" "${suite_name}-manage" \
 		"${suite_name}-cronsetup" "${suite_name}-backup" "${suite_name}-uninstall" "${suite_name}-reset" "validate-cron-schedule.sh" "check-ip-in-registry.sh"
@@ -276,12 +276,12 @@ ln -s "${install_dir}/${suite_name}-manage" "${install_dir}/${suite_name}" ||
 echo -n "Creating backup of current INPUT and FORWARD iptables chains policies... "
 
 # if a backup file already exists, continue installing but skip overwriting the backup file
-if [ -f "$preinstall_policies_file" ]; then
+if [[ -f "$preinstall_policies_file" ]]; then
 	echo "Backup file already exists, skipping creation of iptables policies backup." >&2
 else
 	preinstall_input_policy=$(iptables -nL | grep "Chain INPUT" | awk -F'policy |)' '{print $2}')
 	preinstall_forward_policy=$(iptables -nL | grep "Chain FORWARD" | awk -F'policy |)' '{print $2}')
-	if [ -z "$preinstall_input_policy" ] || [ -z "$preinstall_forward_policy" ]; then
+	if [[ -z "$preinstall_input_policy" || -z "$preinstall_forward_policy" ]]; then
 		install_failed "Error: failed to determine current iptables policies."
 	fi
 	touch "$preinstall_policies_file" || install_failed "Error: failed to create pre-install policies backup file."
@@ -294,14 +294,14 @@ fi
 
 # cd into the install directory
 # exit in case "cd" fails
-[ -n "$install_dir" ] && cd "$install_dir" || install_failed "Error: Couldn't cd into '$install_dir'."
+[[ -n "$install_dir" ]] && cd "$install_dir" || install_failed "Error: Couldn't cd into '$install_dir'."
 
 
 ### Add iplist(s) for $tlds to managed iplists, then fetch and apply the iplist(s)
 ${suite_name}-manage add -f -c "$tlds"; rv=$?
 
 # the *manage script exits with return value 254 if requested country is already included in the config
-if [ $rv -ne 0 ] && [ $rv -ne 254 ]; then
+if [[ $rv -ne 0 && $rv -ne 254 ]]; then
 	install_failed "Failed to create and apply the iplist."
 fi
 
@@ -309,7 +309,7 @@ if [[ ! "$no_persistence" && "$cron_schedule" != "disable" ]]; then
 	### Set up cron jobs
 	${suite_name}-manage schedule -s "$cron_schedule"; rv=$?
 
-	if [ $rv -ne 0 ]; then
+	if [[ $rv -ne 0 ]]; then
 		install_failed "Error: failed to set up cron jobs."
 	fi
 else
diff --git a/geoblocker-bash-manage b/geoblocker-bash-manage
--- a/geoblocker-bash-manage
+++ b/geoblocker-bash-manage
@@ -9,7 +9,7 @@
 me=$(basename "$0")
 
 # check for root
-[ "$EUID" -ne 0 ] && {
+[[ "$EUID" -ne 0 ]] && {
 	err="Error: $me needs to be run as root."
 	echo "$err" >&2
 	exit 1
@@ -17,7 +17,7 @@ me=$(basename "$0")
 
 suite_name="geoblocker-bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-[ -n "$script_dir" ] && cd "$script_dir" || { echo "$me: Error: Couldn't cd into '$script_dir'." >&2; exit 1; }
+[[ -n "$script_dir" ]] && cd "$script_dir" || { echo "$me: Error: Couldn't cd into '$script_dir'." >&2; exit 1; }
 
 source "$script_dir/${suite_name}-common" || { echo "$me: Error: Can't source ${suite_name}-common." >&2; exit 1; }
 
@@ -87,7 +87,7 @@ done
 shift $((OPTIND -1))
 
 # check if there are unprocessed arguments
-[[ "$*" != "" ]] && {
+[[ -n "$*" ]] && {
 	usage
 	err1="Error in arguments. First unrecognized argument: '$1'."
 	err2="Note: If specifying multiple country codes, put them in double quotation marks."
@@ -122,26 +122,26 @@ report_status() {
 	input_policy=$(iptables -nL | grep "Chain INPUT" | awk -F'policy |)' '{print $2}')
 	forward_policy=$(iptables -nL | grep "Chain FORWARD" | awk -F'policy |)' '{print $2}')
 
-	if [ -z "$input_policy" ] || [ -z "$forward_policy" ]; then
+	if [[ -z "$input_policy" || -z "$forward_policy" ]]; then
 		die "Error: failed to determine current policies for INPUT and FORWARD chains."
 	fi
 
 	# check ipsets and iptables rules for active tlds
 	active_tlds="$(find_active_tlds)"; rv=$?
-	[ -z "$active_tlds" ] && echo -e "${red}Warning${no_color}: no firewall rules found for any country codes!" || \
+	[[ -z "$active_tlds" ]] && echo -e "${red}Warning${no_color}: no firewall rules found for any country codes!" || \
 		echo -e "$list_type is configured for country codes: '${yellow}$active_tlds${no_color}'.\n"
 
 	check_tlds_coherency; rv=$?
-	if [ "$rv" -ne 0 ]; then
+	if [[ "$rv" -ne 0 ]]; then
 		echo -e "${red}Error${no_color}: discrepancy detected between the config file and iptables rules!\n" >&2
-		[ "$ipsets_incoherent" = "true" ] && \
+		[[ "$ipsets_incoherent" ]] && \
 			echo "${purple}Warning:${no_color} discrepancy detected between existing geoblocking ipsets and geoblocking firewall rules!\n" >&2
 	else
 		echo -e "Country codes in the firewall rules ${green}match${no_color} the config.\n"
 	fi
 
 	# report INPUT and FORWARD chain policies
-	[ "$input_policy" = "$expected_policy" ] && input_policy_colored="${green}${input_policy}${no_color}" || \
+	[[ "$input_policy" = "$expected_policy" ]] && input_policy_colored="${green}${input_policy}${no_color}" || \
 		input_policy_colored="${red}${input_policy}${no_color}"
 	[[ "$forward_policy" = "$expected_policy" || "$forward_policy" = "DROP" ]] && forward_policy_colored="${green}${forward_policy}${no_color}" || \
 		forward_policy_colored="${red}${forward_policy}${no_color}"
@@ -149,47 +149,47 @@ report_status() {
 
 
 	# check INPUT chain default policy compatibility with list_type
-	[ "$input_policy" != "$expected_policy" ] && {
+	[[ "$input_policy" != "$expected_policy" ]] && {
 				echo -e "${purple}WARNING${no_color}: $list_type functionality requires INPUT chain policy to be '$expected_policy' but it is '$input_policy'."
 				echo -e "${red}$list_type is not functioning${no_color}.";
 				} || echo -e "INPUT chain policy ${green}is compatible${no_color} with $list_type."
 
 	# check FORWARD chain default policy compatibility with list_type
-	[ "$forward_policy" != "$expected_policy" ] && [ "$forward_policy" != "DROP" ] && {
+	[[ "$forward_policy" != "$expected_policy" && "$forward_policy" != "DROP" ]] && {
 				echo -e "${purple}WARNING${no_color}: $list_type functionality recommends FORWARD chain policy to be '$expected_policy' but it is '$forward_policy'."
 				} || echo -e "FORWARD chain policy ${green}is compatible${no_color} with $list_type."
 
 
 	# for a whitelist, report global iptables rules (irrelevant for blacklist)
-	if [ "$list_type" = "whitelist" ]; then
+	if [[ "$list_type" = "whitelist" ]]; then
 		echo -e "\n${yellow}Global iptables rules${no_color} for $suite_name:"
 		global_rules="$(iptables-save | grep "${suite_name}_global")"
-		[ "$global_rules" = "" ] && echo "None.\n" || echo -e "${global_rules}\n"
+		[[ -z "$global_rules" ]] && echo "None.\n" || echo -e "${global_rules}\n"
 	fi
 
 	# report specific rules for the active geoblocking mode
 	echo -e "\n${yellow}$list_type iptables rules${no_color} for $suite_name:"
 	geoblocking_rules="$(iptables -L -v | grep "match-set ${suite_name}" | grep "$expected_rule_type")"
-	[ "$geoblocking_rules" = "" ] && echo -e "${red}None.${no_color}\n\n${red}Error${no_color}: expected geoblocking rules are not found in the firewall!\n" || \
+	[[ -z "$geoblocking_rules" ]] && echo -e "${red}None.${no_color}\n\n${red}Error${no_color}: expected geoblocking rules are not found in the firewall!\n" || \
 		echo -e "$geoblocking_rules\n"
 
 	# check if cron service is enabled
 	(systemctl is-enabled cron.service) > /dev/null || crondisabled="true"
-	if [ -n "$crondisabled" ]; then
+	if [[ -n "$crondisabled" ]]; then
 		echo -e "${purple}WARNING${no_color}: cron service appears to be disabled. Both persistence across reboots and autoupdates will likely not work.\n"
 	else
 		echo -e "Cron system service is ${green}enabled${no_color}.\n"
 
 		# check cron jobs
 		persistence_job="$(crontab -u root -l 2>/dev/null | grep "${suite_name}-persistence")"
-		[ "$persistence_job" != "" ] && echo -e "${green}Persistence cron job is active${no_color}.\n" || \
+		[[ -n "$persistence_job" ]] && echo -e "${green}Persistence cron job is active${no_color}.\n" || \
 			echo -e "${purple}WARNING${no_color}: Persistence cron job is ${red}missing${no_color}. Geoblocking will not work after reboot.\n"
 
 		autoupdate_job="$(crontab -u root -l 2>/dev/null | grep "${suite_name}-autoupdate")"
-		if [ "$autoupdate_job" != "" ]; then
+		if [[ -n "$autoupdate_job" ]]; then
 			echo -e "${green}Autoupdate cron job is active.${no_color}\n"
 			update_schedule="$(echo "$autoupdate_job" | cut -f1 -d\")"
-			if [[ "$update_schedule" != "" && "$update_schedule" != " " ]]; then
+			if [[ -n "$update_schedule" && "$update_schedule" != " " ]]; then
 				echo -e "Autoupdate schedule: ${yellow}$update_schedule${no_color}\n"
 			else
 				echo -e "${red}Error:${no_color} Could not determine autoupdate schedule. Complete cron line:"; echo -e "${autoupdate_job}\n"
@@ -205,8 +205,8 @@ restore_from_config() {
 
 	echo
 	echo -e "Warning: Config incoherence detected between the firewall current status and the config file."
-	[ "$unexpected_tlds" != "" ] && echo "Unexpected tlds in the firewall: '$unexpected_tlds'" >&2
-	[ "$missing_tlds" != "" ] && echo "Missing tlds in the firewall: '$missing_tlds'" >&2
+	[[ -n "$unexpected_tlds" ]] && echo "Unexpected tlds in the firewall: '$unexpected_tlds'" >&2
+	[[ -n "$missing_tlds" ]] && echo "Missing tlds in the firewall: '$missing_tlds'" >&2
 	echo "Would you like to re-apply the rules from the config file to fix this?"
 	echo -e "\n'Y' to re-apply the config rules. 'N' to exit the script. 'S' to show country codes in the config file.\n"
 
@@ -224,27 +224,27 @@ restore_from_config() {
 	echo "Restoring $list_type countries set '$config_tlds' from the config file... "
 	tlds_to_remove="$(merge_lists "$config_tlds" "$unexpected_tlds" "$tlds_to_change")"
 	$run_command remove -o -c "$tlds_to_remove"
-	[[ "$config_tlds" != "" ]] && $run_command add -o -c "$config_tlds"
+	[[ -n "$config_tlds" ]] && $run_command add -o -c "$config_tlds"
 
 	check_tlds_coherency; rv=$?
-	if [ $rv -eq 0 ]; then
+	if [[ $rv -eq 0 ]]; then
 		echo "Successfully re-applied previous $list_type countries set."
 	else
 		echo "Failed to re-apply previous $list_type countries set." >&2
-		[ "$unexpected_tlds" != "" ] && echo "Unexpected $list_type tlds in the firewall: '$unexpected_tlds'" >&2
-		[ "$missing_tlds" != "" ] && echo "Missing $list_type tlds in the firewall: '$missing_tlds'" >&2
-		[ "$ipsets_incoherent" = "true" ] && echo "Warning: discrepancy detected between existing geoblocking ipsets and geoblocking firewall rules!" >&2
+		[[ -n "$unexpected_tlds" ]] && echo "Unexpected $list_type tlds in the firewall: '$unexpected_tlds'" >&2
+		[[ -n "$missing_tlds" ]] && echo "Missing $list_type tlds in the firewall: '$missing_tlds'" >&2
+		[[ "$ipsets_incoherent" ]] && echo "Warning: discrepancy detected between existing geoblocking ipsets and geoblocking firewall rules!" >&2
 		# call the *backup script to initiate recovery from fault
 		${suite_name}-backup restore; rv=$?
 
 		check_tlds_coherency; rv1=$?; rv=$(( rv + rv1 ))
-		if [ $rv -eq 0 ]; then
+		if [[ $rv -eq 0 ]]; then
 			echo "Successfully re-applied previous $list_type countries set."
 		else
 			echo "Failed to re-apply previous $list_type countries set." >&2
-			[ "$unexpected_tlds" != "" ] && echo "Unexpected $list_type tlds in the firewall: '$unexpected_tlds'" >&2
-			[ "$missing_tlds" != "" ] && echo "Missing $list_type tlds in the firewall: '$missing_tlds'" >&2
-			[ "$ipsets_incoherent" = "true" ] && echo "Warning: discrepancy detected between existing geoblocking ipsets and geoblocking firewall rules!" >&2
+			[[ -n "$unexpected_tlds" ]] && echo "Unexpected $list_type tlds in the firewall: '$unexpected_tlds'" >&2
+			[[ -n "$missing_tlds" ]] && echo "Missing $list_type tlds in the firewall: '$missing_tlds'" >&2
+			[[ "$ipsets_incoherent" ]] && echo "Warning: discrepancy detected between existing geoblocking ipsets and geoblocking firewall rules!" >&2
 			die "$rv" "Something is not working as it should. Consider fixing your firewall or your system. If it's a bug then please report it."
 		fi
 	fi
@@ -291,13 +291,13 @@ run_command="${install_dir}/${suite_name}-run"
 missing_deps="$(check_deps "curl|wget" jq iptables-save iptables-restore ipset)" || die "Error: missing dependencies: $missing_deps."
 
 # check that the config file exists
-[ ! -f "$conf_file" ] && die "Config file '$conf_file' doesn't exist! Run the installation script again."
+[[ ! -f "$conf_file" ]] && die "Config file '$conf_file' doesn't exist! Run the installation script again."
 
-[ -z "$list_type" ] && die "\$list_type variable should not be empty! Something is wrong!"
+[[ -z "$list_type" ]] && die "\$list_type variable should not be empty! Something is wrong!"
 
 ## Check arguments for sanity
 
-[ -z "$action" ] && { usage; die "Specify action!"; }
+[[ -z "$action" ]] && { usage; die "Specify action!"; }
 
 case "$action" in
 	add) ;;
@@ -307,16 +307,16 @@ case "$action" in
 	*) usage; die "Error: unsupported action '$action'." ;;
 esac
 
-[[ ("$action" == "add" || "$action" == "remove") && -z "$tlds_arg" ]] && \
+[[ ("$action" = "add" || "$action" = "remove") && -z "$tlds_arg" ]] && \
 	die "Error: action '$action' requires to specify countries with '-c <tlds>'!"
 
-[[ "$action" == "schedule" && ( -n "$tlds_arg" || -n "$force_action" ) ]] && \
+[[ "$action" = "schedule" && ( -n "$tlds_arg" || -n "$force_action" ) ]] && \
 	die "Action '$action' only supports changing the cron schedule! Do not use it with any option except '-s' or '-d' !"
 
-[[ "$action" == "status" && ( -n "$tlds_arg" || -n "$force_action" ) ]] && \
+[[ "$action" = "status" && ( -n "$tlds_arg" || -n "$force_action" ) ]] && \
 	die "Command '$action' only supports checking on current status of geoblocking! Do not use it with any option except '-l' or '-d' !"
 
-[ "$action" != "schedule" ] && [ -n "$cron_schedule" ] && {
+[[ "$action" != "schedule" && -n "$cron_schedule" ]] && {
 	msg1="Error: the '-s <\"cron_schedule\">' option only works with the \"schedule\" action."
 	msg2="To set up cron schedule, use '$me schedule -s <\"cron_schedule\">'"
 	usage
@@ -329,7 +329,7 @@ esac
 # check config coherency vs active ipsets and firewall rules before performing any action
 check_tlds_coherency || restore_from_config
 
-if [ "$action" = "status" ]; then
+if [[ "$action" = "status" ]]; then
 	report_status
 	unset list_type
 	unset debugmode
@@ -345,14 +345,14 @@ case "$action" in
 		requested_planned_tlds="$(merge_lists "$config_tlds" "$tlds_arg")"
 #		debugprint "requested resulting tlds: '$requested_planned_tlds'"
 
-		if [ -z "$force_action" ]; then
+		if [[ -z "$force_action" ]]; then
 			# remove any entries already present in config_tlds from tlds_arg and assign to tlds_to_change
 			tlds_to_change="$(find_lists_difference "$config_tlds" "$requested_planned_tlds")"
 
 			# find which tlds were specified for addition but already exist
 			wrong_tlds="$(find_lists_intersection "$tlds_arg" "$config_tlds")"
 
-			[ "$wrong_tlds" != "" ] && echo "NOTE: countries '$wrong_tlds' have already been added to the $list_type." >&2
+			[[ -n "$wrong_tlds" ]] && echo "NOTE: countries '$wrong_tlds' have already been added to the $list_type." >&2
 		else
 			tlds_to_change="$tlds_arg"
 		fi
@@ -362,13 +362,13 @@ case "$action" in
 
 	remove)
 #		debugprint "requested tlds to remove: '$tlds_arg'"
-		if [ -z "$force_action" ]; then
+		if [[ -z "$force_action" ]]; then
 			# find duplicate-free intersection between config_tlds and tlds_arg
 			tlds_to_change="$(find_lists_intersection "$config_tlds" "$tlds_arg")"
 			# find which tlds were specified for removal but don't exist
 			good_tlds="$(find_lists_intersection "$tlds_to_change" "$tlds_arg")"
 			wrong_tlds="$(find_lists_difference "$tlds_arg" "$good_tlds")"
-			[ "$wrong_tlds" != "" ] && echo "NOTE: countries '$wrong_tlds' have not been added to the $list_type, so can not remove." >&2
+			[[ -n "$wrong_tlds" ]] && echo "NOTE: countries '$wrong_tlds' have not been added to the $list_type, so can not remove." >&2
 
 		else
 			tlds_to_change="$tlds_arg"
@@ -379,11 +379,11 @@ case "$action" in
 esac
 
 
-if [ "$action" != "add" ] && [ "$action" != "remove" ]; then
+if [[ "$action" != "add" && "$action" != "remove" ]]; then
 	debugprint "Skipping the *run script call because specified action was '$action'."
 else
 
-	if [ -z "$tlds_to_change" ] && [ -z "$force_action" ]; then
+	if [[ -z "$tlds_to_change" && -z "$force_action" ]]; then
 		config_tlds="$(getconfig "Countries")" || die "Error: Couldn't read value for Countries from the config file."
 		echo -e "\nCountries in final $list_type: '${yellow}$config_tlds${no_color}'."
 		die 254 "Nothing to do, exiting."
@@ -402,10 +402,10 @@ else
 	$run_command "$action" -c "$tlds_to_change"; rv=$?
 
 	# positive return code means apply failure or another permanent error, except for 254
-	if [ $rv -gt 0 ] && [ $rv -ne 254 ]; then
+	if [[ $rv -gt 0 && $rv -ne 254 ]]; then
 		echo "Error performing action '$action' for countries '$tlds_to_change'." >&2
 
-		if [ "$config_tlds" = "" ]; then
+		if [[ -z "$config_tlds" ]]; then
 			die "Can not restore previous countries set for the $list_type because it is not found in the config file."
 		fi
 		restore_from_config
@@ -414,15 +414,15 @@ else
 	new_verified_tlds="$(find_active_tlds)"
 	failed_tlds="$(find_lists_difference "$new_verified_tlds" "$planned_tlds")"
 
-	if [ "$failed_tlds" != "" ]; then
+	if [[ -n "$failed_tlds" ]]; then
 		debugprint "planned_tlds: '$planned_tlds', new_verified_tlds: '$new_verified_tlds', failed_tlds: '$failed_tlds'."
 		echo "Warning: failed to apply new $list_type rules for countries: $failed_tlds." >&2
 		# if the error encountered during installation, exit with error in order to fail the installation
-		[ "$in_install" ] && die
+		[[ "$in_install" ]] && die
 	fi
 
 	# if all 'add' actions failed
-	if [ -z "$(find_lists_difference "$tlds_to_change" "$failed_tlds")" ]; then
+	if [[ -z "$(find_lists_difference "$tlds_to_change" "$failed_tlds")" ]]; then
 		die "All actions failed."
 	fi
 
@@ -442,28 +442,28 @@ else
 
 	echo -e "\nCountries in final $list_type: '${yellow}$config_tlds${no_color}'."
 	echo
-	[ ! "$in_install" ] && echo -e "View current geoblocking status with '${yellow}sudo ${suite_name} status${no_color}'\n"
+	[[ ! "$in_install" ]] && echo -e "View current geoblocking status with '${yellow}sudo ${suite_name} status${no_color}'\n"
 fi
 
 
 ### Cron jobs management
-if [ "$action" != "schedule" ]; then
+if [[ "$action" != "schedule" ]]; then
 	debugprint "Skipping cron setup because action is not 'schedule'."
 else
-	[[ "$cron_schedule" == "" ]] && cron_schedule="disable"
+	[[ -z "$cron_schedule" ]] && cron_schedule="disable"
 
 	# write to the config file in order to communicate parameters to *cronsetup
 	setconfig "CronSchedule=$cron_schedule" || die "Failed to write the updated CronSchedule value to the config file"
 
 	${suite_name}-cronsetup; rv=$?
-	if [ "$rv" -eq 0 ]; then
+	if [[ "$rv" -eq 0 ]]; then
 		echo -e "\nView current cron jobs with 'sudo crontab -l'"
 	else
 		die "Error: Failed to create or update cron jobs."
 	fi
 fi
 
-[ ! "$in_install" ] && echo
+[[ ! "$in_install" ]] && echo
 
 debugexitmsg
 
diff --git a/geoblocker-bash-reset b/geoblocker-bash-reset
--- a/geoblocker-bash-reset
+++ b/geoblocker-bash-reset
@@ -10,20 +10,20 @@
 me=$(basename "$0")
 
 # check for root
-[ "$EUID" -ne 0 ] && {
+[[ "$EUID" -ne 0 ]] && {
 	err="Error: $me needs to be run as root."
 	echo "$err" >&2
-	[ ! "$nolog" ] && logger "$err"
+	[[ ! "$nolog" ]] && logger "$err"
 	exit 1
 }
 
 suite_name="geoblocker-bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-[ -n "$script_dir" ] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
-	[ ! "$nolog" ] && logger "$err"; exit 1; }
+[[ -n "$script_dir" ]] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
+	[[ ! "$nolog" ]] && logger "$err"; exit 1; }
 
 source "$script_dir/${suite_name}-common" || { err="$me: Error: Can't source ${suite_name}-common."; echo "$err" >&2; \
-	[ ! "$nolog" ] && logger "$err"; exit 1; }
+	[[ ! "$nolog" ]] && logger "$err"; exit 1; }
 
 # **NOTE** that some functions and variables are sourced from the *common script
 
@@ -58,7 +58,7 @@ while getopts ":dh" opt; do
 done
 shift $((OPTIND -1))
 
-[[ "$*" != "" ]] && {
+[[ -n "$*" ]] && {
 	usage
 	echo "Error in arguments. First unrecognized argument: '$1'." >&2
 	echo "Note: If specifying multiple country codes, put them in double braces." >&2
@@ -79,7 +79,7 @@ debugentermsg
 
 # get datadir from the config file
 datadir="$(getconfig "Datadir")"; rv=$?
-if [ "$rv" -ne 0 ] || [ -z "$datadir" ]; then datadir="/var/lib/${suite_name}"; fi
+if [[ "$rv" -ne 0 || -z "$datadir" ]]; then datadir="/var/lib/${suite_name}"; fi
 
 preinstall_policies_file="$datadir/preinstall_policies.bak"
 
@@ -99,12 +99,12 @@ debugprint "Deleting cron jobs for ${suite_name}..."
 crontab -u root -l 2>/dev/null |  grep -v "${suite_name}-run" | sudo crontab -u root -
 
 
-if [ -f "$preinstall_policies_file" ]; then
+if [[ -f "$preinstall_policies_file" ]]; then
 	### Restore iptables policies to pre-install state
 	while read -r preinstall_policy; do
 		chain_name=$(echo "$preinstall_policy" | cut -f 1 -d " ")
 		oldpolicy=$(echo "$preinstall_policy" | cut -f 2 -d " ")
-		if [ -n "$chain_name" ] && [ -n "$oldpolicy" ]; then
+		if [[ -n "$chain_name" && -n "$oldpolicy" ]]; then
 			debugprint "Restoring pre-install iptables policy '$oldpolicy' for chain '$chain_name'"
 			iptables -P "$chain_name" "$oldpolicy" &> /dev/null
 		fi
diff --git a/geoblocker-bash-run b/geoblocker-bash-run
--- a/geoblocker-bash-run
+++ b/geoblocker-bash-run
@@ -18,20 +18,20 @@
 me=$(basename "$0")
 
 # check for root
-[ "$EUID" -ne 0 ] && {
+[[ "$EUID" -ne 0 ]] && {
 	err="Error: $me needs to be run as root."
 	echo "$err" >&2
-	[ ! "$nolog" ] && logger "$err"
+	[[ ! "$nolog" ]] && logger "$err"
 	exit 1
 }
 
 suite_name="geoblocker-bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-[ -n "$script_dir" ] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
-	[ ! "$nolog" ] && logger "$err"; exit 1; }
+[[ -n "$script_dir" ]] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
+	[[ ! "$nolog" ]] && logger "$err"; exit 1; }
 
 source "$script_dir/${suite_name}-common" || { err="$me: Error: Can't source ${suite_name}-common."; echo "$err" >&2; \
-	[ ! "$nolog" ] && logger "$err"; exit 1; }
+	[[ ! "$nolog" ]] && logger "$err"; exit 1; }
 
 # **NOTE** that some functions and variables are sourced from the *common script
 
@@ -93,7 +93,7 @@ while getopts ":c:osdh" opt; do
 done
 shift $((OPTIND -1))
 
-[ "$*" != "" ] && {
+[[ -n "$*" ]] && {
 	usage
 	err1 "Error in arguments. First unrecognized argument: '$1'."
 	err2="Note: If specifying multiple country codes, put them in double quotation marks."
@@ -116,7 +116,7 @@ debugentermsg
 # Read current set of countries from the the config file into config_tlds
 config_tlds="$(getconfig "Countries")" || die "Error: Couldn't read value for Countries from the config file."
 
-if [ -z "$arg_tlds" ] || [ "$action_run" = "update" ]; then
+if [[ -z "$arg_tlds" || "$action_run" = "update" ]]; then
 	tlds="$config_tlds"
 else
 	tlds="$arg_tlds"
@@ -152,36 +152,22 @@ failed_tlds_cnt=0
 
 #### CHECKS
 
-missing_deps="$(check_deps "curl|wget" jq iptables-save iptables-restore ipset)" || die "Error: missing dependencies: $missing_deps."
+missing_deps="$(check_deps "curl|wget" jq iptables-save iptables-restore ipset ${suite_name}-fetch ${suite_name}-apply ${suite_name}-backup)" \
+	|| die "Error: missing dependencies: $missing_deps."
 
 # check that the config file exists
-[ ! -f "$conf_file" ] && die "Config file '$conf_file' doesn't exist! Run the installation script again."
+[[ ! -f "$conf_file" ]] && die "Config file '$conf_file' doesn't exist! Run the installation script again."
 
-[ -z "$knowngood_file" ] && die "Error: Known-good file path can not be empty! Exiting."
+[[ -z "$knowngood_file" ]] && die "Error: Known-good file path can not be empty! Exiting."
 
-[ -z "$iplist_dir" ] && die "Error: iplist file path can not be empty! Exiting."
-
-# check for *fetch
-[ ! "$skipfetch" ] && if ! command -v ${suite_name}-fetch &> /dev/null; then
-	die "Error: Can not find '${suite_name}-fetch'. Did you run setup? Exiting."
-fi
-
-# check for *apply
-if ! command -v ${suite_name}-apply &> /dev/null; then
-	die "Error: Can not find '${suite_name}-apply'. Did you run setup? Exiting."
-fi
-
-# check for *backup
-if ! command -v ${suite_name}-backup &> /dev/null; then
-	die "Error: Can not find '${suite_name}-backup'. Did you run setup? Exiting."
-fi
+[[ -z "$iplist_dir" ]] && die "Error: iplist file path can not be empty! Exiting."
 
 # check for country tlds
-[ -z "$tlds" ] && { err="tlds variable can not be empty! Exiting."; usage; die "$err"; }
+[[ -z "$tlds" ]] && { err="tlds variable can not be empty! Exiting."; usage; die "$err"; }
 
 # check for valid action
 
-[ -z "$action_run" ] && { usage; die "Specify action!"; }
+[[ -z "$action_run" ]] && { usage; die "Specify action!"; }
 
 # translate *run action to *apply action
 case "$action_run" in
@@ -191,14 +177,14 @@ case "$action_run" in
 	*) usage; die "Error: unsupported action '$action_run'" ;;
 esac
 
-[ -z "$list_type" ] && die "\$list_type variable should not be empty! Something is wrong!"
+[[ -z "$list_type" ]] && die "\$list_type variable should not be empty! Something is wrong!"
 
 #### MAIN
 
 
 ### Fetch ip lists
 
-if [ ! "$skipfetch" ] && [ "$action_run" != "remove" ]; then
+if [[ ! "$skipfetch" && "$action_run" != "remove" ]]; then
 
 	# mark all tlds as failed in the status file before launching *fetch. if *fetch completes successfully, it will reset this
 	setstatus "$status_file" "failed_tlds=$tlds" || die "Error: Failed to write to status file '$status_file'."
@@ -209,13 +195,11 @@ if [ ! "$skipfetch" ] && [ "$action_run" != "remove" ]; then
 	tlds_to_update="$(getstatus "$status_file" "tlds_to_update")" || { die "Error: Couldn't read value for 'tlds_to_update' from status file '$status_file'."; }
 	failed_tlds="$(getstatus "$status_file" "failed_tlds")" || { die "Error: Couldn't read value for 'failed_tlds' from status file '$status_file'."; }
 
-	if [ "$failed_tlds" != "" ]; then
-		echolog -err "Failed to fetch and validate subnet lists for countries '$failed_tlds'."
-	fi
+	[[ -n "$failed_tlds" ]] && echolog -err "Failed to fetch and validate subnet lists for countries '$failed_tlds'."
 
 	failed_tlds_cnt=$(echo "$failed_tlds" | wc -w)
 
-	[ "$failed_tlds_cnt" -ge "$tlds_cnt" ] && die 254 "All fetch attempts failed."
+	[[ "$failed_tlds_cnt" -ge "$tlds_cnt" ]] && die 254 "All fetch attempts failed."
 
 else
 	tlds_to_update="$tlds"
@@ -227,21 +211,21 @@ echo
 
 ### Apply ip lists
 
-if [ "$tlds_to_update" = "" ]; then
+if [[ -z "$tlds_to_update" ]]; then
 	echolog "Ip lists don't require firewall reconfiguration."
 else
-	if [ -z "$nobackup" ]; then
+	if [[ -z "$nobackup" ]]; then
 		# check config coherency vs active ipsets and firewall rules before creating backup
 		check_tlds_coherency; rv=$?
-		if [ $rv -eq 0 ]; then
+		if [[ $rv -eq 0 ]]; then
 			# call the backup script to create a known-good backup of ipsets and iptables state
 			${suite_name}-backup create-backup
 		else
 			echolog -err "Warning: actual $list_type firewall config differs from the config file!"
 			echolog -err "Please run the *manage script to restore config coherency!"
 			echolog -err "If it's a recurring issue, please consider filing a bug report!"
-			[ "$unexpected_tlds" != "" ] && echolog -err "Unexpected country codes in the firewall: '$unexpected_tlds'"
-			[ "$missing_tlds" != "" ] && echolog -err "Missing country codes in the firewall: '$missing_tlds'"
+			[[ -n "$unexpected_tlds" ]] && echolog -err "Unexpected country codes in the firewall: '$unexpected_tlds'"
+			[[ -n "$missing_tlds" ]] && echolog -err "Missing country codes in the firewall: '$missing_tlds'"
 			echo
 		fi
 	else
@@ -250,27 +234,27 @@ else
 
 	${suite_name}-apply "$action_apply" -c "$tlds_to_update"; rv=$?
 
-#	[ "$testmode" ] && rv=1
+#	[[ "$testmode" ]] && rv=1
 
-	if [ $rv -eq 254 ]; then
+	if [[ $rv -eq 254 ]]; then
 		debugprint "NOTE: *apply exited with error code 254."
-		echo ""
+		echo
 		echolog -err "Error: *apply exited with code '254'. Failed to apply action '$action_apply'."
-	elif [ $rv -gt 0 ] && [ $rv -ne 254 ]; then
+	elif [[ $rv -gt 0 && $rv -ne 254 ]]; then
 		debugprint "NOTE: *apply exited with error code '$rv'."
-		echo ""
+		echo
 		# if fatal errors occur in *apply, attempt to restore last known-good ipsets and iptables state
 		# if we're in install, skip this step because there is no backup of ipsets anyway
-		[ ! "$in_install" ] && ${suite_name}-backup restore; rv="$?"
+		[[ ! "$in_install" ]] && ${suite_name}-backup restore; rv="$?"
 
 		# exit with the same exit code as backup-restore operation
-		die "$rv" ""
+		die "$rv"
 	else
 		echolog "Successfully applied action '$action_run' for countries '$tlds_to_update'."
 	fi
 fi
 
-if [ "$failed_tlds_cnt" -ne 0 ]; then
+if [[ "$failed_tlds_cnt" -ne 0 ]]; then
 	debugprint "failed_tlds_cnt: $failed_tlds_cnt"
 	rv=254
 else
@@ -278,5 +262,8 @@ else
 fi
 
 debugexitmsg
+
+unset debugmode
+unset list_type
 
 exit "$rv"
diff --git a/geoblocker-bash-uninstall b/geoblocker-bash-uninstall
--- a/geoblocker-bash-uninstall
+++ b/geoblocker-bash-uninstall
@@ -10,7 +10,7 @@
 me=$(basename "$0")
 
 # check for root
-[ "$EUID" -ne 0 ] && {
+[[ "$EUID" -ne 0 ]] && {
 	err="Error: $me needs to be run as root."
 	echo "$err" >&2
 	exit 1
@@ -18,7 +18,7 @@ me=$(basename "$0")
 
 suite_name="geoblocker-bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-[ -n "$script_dir" ] && cd "$script_dir" || { echo "Error: Couldn't cd into '$script_dir'." >&2; exit 1; }
+[[ -n "$script_dir" ]] && cd "$script_dir" || { echo "Error: Couldn't cd into '$script_dir'." >&2; exit 1; }
 
 source "$script_dir/${suite_name}-common" || { echo "Error: Can't source ${suite_name}-common." >&2; exit 1; }
 
@@ -58,7 +58,7 @@ while getopts ":dh" opt; do
 done
 shift $((OPTIND -1))
 
-[[ "$*" != "" ]] && {
+[[ -n "$*" ]] && {
 	usage
 	echo "Error in arguments. First unrecognized argument: '$1'." >&2
 	exit 1
@@ -79,7 +79,7 @@ debugentermsg
 install_dir="/usr/local/bin"
 
 datadir="$(getconfig "Datadir")"; rv=$?
-if [ "$rv" -ne 0 ] || [ -z "$datadir" ]; then datadir="/var/lib/${suite_name}"; fi
+if [[ "$rv" -ne 0 || -z "$datadir" ]]; then datadir="/var/lib/${suite_name}"; fi
 preinstall_policies_file="$datadir/preinstall_policies.bak"
 iptables_comment="$suite_name"
 
@@ -89,14 +89,14 @@ crontab -u root -l 2>/dev/null |  grep -v "${suite_name}-run" | sudo crontab -u 
 
 ### Restore pre-install state of default policies for INPUT and FORWARD chains
 
-if [ -f "$preinstall_policies_file" ]; then
+if [[ -f "$preinstall_policies_file" ]]; then
 	while read -r preinstall_policy; do
 		chain_name=$(echo "$preinstall_policy" | cut -f 1 -d " ")
 		oldpolicy=$(echo "$preinstall_policy" | cut -f 2 -d " ")
-		if [ -n "$chain_name" ] && [ -n "$oldpolicy" ]; then
+		if [[ -n "$chain_name" && -n "$oldpolicy" ]]; then
 			echo "Restoring pre-install iptables policy '$oldpolicy' for chain '$chain_name'"
 			iptables -P "$chain_name" "$oldpolicy"; rv=$?
-			if [ $rv -ne 0 ]; then
+			if [[ $rv -ne 0 ]]; then
 				echo "Error $rv trying to change iptables policy with command 'iptables -P $chain_name $oldpolicy'. Exiting." >&2
 				exit 1
 				fi
