*install: multiple changes - improved the description - improved the Usage function - use full path to the -common script when sourcing it - call the sanitize_args() function from the main script (instead of from the -common script) - export the debug mode setting to an env variable - changed the way no_persistence value is acquired from arguments. no more separate argument for that, now allows for the "disable" value instead of cron schedule expression. - write the no_drop value to config, don't provide it to the -manage script via an argument - don't write backup_script value to the config file (it's unused) - added support for the new -cronsetup script - don't specify file path to the config file to conform to the updated API of the getconfig() and setconfig() functions in the -common script - write the no_persistence value to config, don't provide it to the -manage script via an argument - compacted a debug message - removed irrelevant comment - to conform to the new -manage script api, call it twice: first time to configure, fetch and apply tlds, second time to configure and apply cron schedule

diff --git a/geoblocker_bash-install b/geoblocker_bash-install
--- a/geoblocker_bash-install
+++ b/geoblocker_bash-install
@@ -8,20 +8,29 @@
 # Creates system folder structure for scripts, config and data.
 # Copies all scripts included in the suite to /usr/local/bin.
 # Creates backup of pre-install policies for INPUT and FORWARD chains.
-# Calls geoblocker_bash-manage to set up geoblocker and then call the -fetch and -apply scripts.
+# Calls geoblocker_bash-manage to set up geoblocker.
 # If an error occurs during installation, calls the uninstall script to revert any changes made to the system.
 # Accepts a custom cron schedule expression as an argument. Default cron schedule is "0 4 * * *" - at 4:00 [am] every day.
 
 # Requires the following additional scripts (included in the distribution):
 # geoblocker_bash-fetch, geoblocker_bash-apply, geoblocker_bash-run, geoblocker_bash-uninstall, validate_cron_schedule.sh, check_ip_in_ripe.sh
 
+
+#### Initial setup
+
 me=$(basename "$0")
 suite_name="geoblocker_bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 [ -n "$script_dir" ] && cd "$script_dir" || { echo "Error: Couldn't cd into '$script_dir'."; exit 1; }
 
-source "${suite_name}-common" || { echo "Error: Can't find ${suite_name}-common."; exit 1; }
+source "$script_dir/${suite_name}-common" || { echo "Error: Can't find ${suite_name}-common."; exit 1; }
 # NOTE that some functions and variables are sourced from the *common script
+
+# sanitize arguments
+sanitize_args "$@"
+# replace arguments with sanitized ones
+set -- "${arguments[@]}"
+
 
 #### USAGE
 
@@ -36,41 +45,45 @@ Must be run as root.
 This script:
 1) Creates system folder structure for scripts, config and data.
 2) Copies all scripts included in the suite to /usr/local/bin.
-3) Creates backup of pre-install policies for INPUT and FORWARD chains.
+3) Creates backup of pre-install policies for INPUT and FORWARD iptables chains.
 4) Calls ${suite_name}-manage to set up geoblocker and then call the -fetch and -apply scripts.
 5) If an error occurs during installation, calls the uninstall script to revert any changes made to the system.
 6) Accepts a custom cron schedule expression as an argument. Default cron schedule is "0 4 * * *" - at 4:00 [am] every day.
 
-    Usage: $me -c <"tld [tld] ... [tld]"> [-s "<schedule_expression>"] [-n] [-p] [-d] [-h]
+Usage: $me -c <"tld [tld] ... [tld]"> [-s <"sch_expression">|disable] [-p] [-d] [-h]
 
-    Options:
-        -c <"tld(s)">        : tld / country codes. if passing multiple country codes, use double quotes
-        -s "sch_expression"  : schedule expression for the cron job, must be inside double quotes
-                                  default: "0 4 * * *" (at 4:00 [am] every day)
+Options:
+    -c <"tld(s)">                 : tld / country codes. if passing multiple country codes, use double quotes
+    -s <"sch_expression">|disable : schedule expression for the periodic cron job, must be inside double quotes
+                                           default: "0 4 * * *" (at 4:00 [am] every day)
+                                    "disable" turns off persistence
 
-        -p                   : No Drop: applies the config but skips setting INPUT chain default policy to DROP
-        -n                   : No persistence (will not create cron jobs)
-        -d                   : Debug
-        -h                   : This help
+    -p                            : No Drop: applies the config but skips setting INPUT chain default policy to DROP
+    -d                            : Debug
+    -h                            : This help
 
 EOF
 }
 
 #### PARSE ARGUMENTS
 
-while getopts "c:s:npdh" opt; do
+while getopts "c:s:pdh" opt; do
 	case $opt in
 		c) tlds=$OPTARG;;
 		s) cron_schedule=$OPTARG;;
-		n) no_persistence="-n";;
-		p) nodrop="-p";;
-		d) debug="-d";;
+		p) nodrop="true";;
+		d) debugmode_args="true";;
 		h) usage; exit 0;;
 		\?) usage; exit 1;;
 	esac
 done
 
-echo ""
+echo
+
+# get debugmode variable from either the args or environment variable
+debugmode="${debugmode_args:-$debugmode}"
+# set env var to match the result
+export debugmode="$debugmode"
 
 # Print script enter message for debug
 debugentermsg
@@ -118,11 +131,12 @@ datadir="/var/lib/${suite_name}"
 preinstall_policies_file="${datadir}/preinstall_policies.bak"
 knowngood_file="${datadir}/iptables_knowngood.bak"
 whitelist_dir="${datadir}/ip_lists"
-backup_script="${install_dir}/${suite_name}-backup"
 
 default_schedule="0 4 * * *"
 cron_schedule="${cron_schedule:-$default_schedule}"
 sleeptime="30"
+
+[ "$cron_schedule" = "disable" ] && no_persistence="true"
 
 #### CHECKS
 
@@ -205,6 +219,7 @@ check_file_exists "${suite_name}-common"
 check_file_exists "${suite_name}-apply"
 check_file_exists "${suite_name}-run"
 check_file_exists "${suite_name}-manage"
+check_file_exists "${suite_name}-cronsetup"
 check_file_exists "${suite_name}-backup"
 check_file_exists "${suite_name}-uninstall"
 check_file_exists "validate_cron_schedule.sh"
@@ -218,11 +233,14 @@ mkdir -p "$conf_dir"
 
 # write some config to the config file
 echo -n "Setting initial config... "
-setconfig "Installdir" "$conf_file" "$install_dir"; rv=$(( rv + $?))
-setconfig "Datadir" "$conf_file" "$datadir"; rv=$(( rv + $?))
-setconfig "Cron_schedule" "$conf_file" "$cron_schedule"; rv=$(( rv + $?))
-setconfig "RebootSleep" "$conf_file" "$sleeptime"; rv=$(( rv + $?))
-setconfig "Backup_script" "$conf_file" "$backup_script"; rv=$(( rv + $?))
+setconfig "Installdir" "$install_dir"; rv=$(( rv + $?))
+setconfig "Datadir" "$datadir"; rv=$(( rv + $?))
+[ "$cron_schedule" != "disable" ] && { setconfig "CronSchedule" "$cron_schedule"; rv=$(( rv + $?)); }
+setconfig "DefaultSchedule" "0 4 * * *"; rv=$(( rv + $?))
+setconfig "RebootSleep" "$sleeptime"; rv=$(( rv + $?))
+setconfig "Backup_script" "$backup_script"; rv=$(( rv + $?))
+setconfig "NoPersistence" "$no_persistence"; rv=$(( rv + $?))
+setconfig "NoDrop" "$nodrop"; rv=$(( rv + $?))
 if [ "$rv" -ne 0 ]; then
 	echo "Failed."
 	install_failed
@@ -260,6 +278,7 @@ if [ "$script_dir" != "$install_dir" ]; then
 	copyscript "${suite_name}-apply" "${install_dir}/"
 	copyscript "${suite_name}-run" "${install_dir}/"
 	copyscript "${suite_name}-manage" "${install_dir}/"
+	copyscript "${suite_name}-cronsetup" "${install_dir}/"
 	copyscript "${suite_name}-backup" "${install_dir}/"
 	copyscript "${suite_name}-uninstall" "${install_dir}/"
 	copyscript "validate_cron_schedule.sh" "${install_dir}/"
@@ -290,8 +309,7 @@ else
 	echo "INPUT $preinstall_input_policy" >> "$preinstall_policies_file"
 	echo "FORWARD $preinstall_forward_policy" >> "$preinstall_policies_file"
 	echo "Ok."
-	debugprint "Current policies:"
-	debugprint "INPUT: $preinstall_input_policy, FORWARD: $preinstall_forward_policy"
+	debugprint "Current policies:   INPUT: $preinstall_input_policy, FORWARD: $preinstall_forward_policy"
 fi
 
 # cd into the install directory
@@ -299,11 +317,18 @@ fi
 [ -n "$install_dir" ] && cd "$install_dir" || { echo "Error: Couldn't cd into '$install_dir'. Exiting."; install_failed; }
 
 ### Add whitelist(s) for $tlds to managed whitelists, then fetch and apply the whitelist(s)
-# have to use array to prevent getopts errors. have to provide cron schedule separately to prevent * expansion
-${suite_name}-manage "$debug" "$no_persistence" "$nodrop" -f -a "add" -c "$tlds" -s "$cron_schedule"; rv=$?
+${suite_name}-manage -f -a "add" -c "$tlds"; rv=$?
 
 # the *manage script exits with return value 254 if requested country is already included in the config
 if [ $rv -ne 0 ] && [ $rv -ne 254 ]; then
+	echo "Failed to create and apply the whitelist."
+	install_failed
+fi
+
+### Set up cron jobs
+${suite_name}-manage -a "schedule" -s "$cron_schedule"; rv=$?
+
+if [ $rv -ne 0 ]; then
 	echo "Failed to create and apply the whitelist."
 	install_failed
 fi
@@ -313,5 +338,6 @@ echo "Install done."
 echo ""
 
 unset nolog
+unset debugmode
 
 exit 0
