multiple improvements
- Improved the description
- Improved console output messages
- Exit when detecting wrong command line arguments
- Output backup file location to console before attempting to overwrite that file (for user's reference)

diff --git a/geoblocker_bash-apply b/geoblocker_bash-apply
--- a/geoblocker_bash-apply
+++ b/geoblocker_bash-apply
@@ -5,11 +5,11 @@
 # Creates or updates an ipset from a user-specified whitelist file (which should contain a plain ipv4 subnets list).
 # Creates iptables rules that allow connection from subnets included in the ipset
 # Sets default policy on INPUT and FORWARD iptables chains to DROP
-# Saves backup of the current (known-good) iptables state and current ipset
-# In case of an error, attempts to restore last known-good state from the backup
-# If that fails, the script assumes that something is horribly broken and runs the uninstall script
-#        which will attempt to remove any rules we have set, delete cron jobs
-#        and restore policies for INPUT and FORWARD chains to pre-install state
+# Creates backup of the current (known-good) iptables state and current ipset
+# In case of an error, attempts to restore last known-good state from backup
+# If that fails, the script assumes that something is broken and runs the uninstall script
+#        which will attempt to remove any rules we have set, delete associated cron jobs
+#        and restore policies for INPUT and FORWARD chains to the pre-install state
 #
 # Requires the 'ipset' utility. To install it on Debian or derivatives, use the command:
 ## apt install ipset
@@ -23,13 +23,14 @@ me=$(basename "$0")
 
 usage() {
     cat <<EOF
+
 This script:
 1) Creates or updates an ipset from a user-specified whitelist file (which should contain a plain ipv4 subnets list).
 2) Creates iptables rules that allow connection from subnets included in the ipset
 3) Sets default policy on INPUT and FORWARD iptables chains to DROP
 4) Creates backup of the current (known-good) iptables state and current ipset
-5) In case of an error, attempts to restore last known-good state from the backup
-6) If that fails, the script assumes that something is horribly broken and runs the uninstall script
+5) In case of an error, attempts to restore last known-good state from backup
+6) If that fails, the script assumes that something is broken and runs the uninstall script
         which will attempt to remove any rules we have set, delete the associated cron jobs
         and restore policies for INPUT and FORWARD chains to the pre-install state
 
@@ -55,6 +56,7 @@ while getopts "p:f:k:dht" opt; do
 		d) debug=true;;
 		h) usage; exit 0;;
 		t) test=true;;
+		\?) usage; exit 1;;
 	esac
 done
 shift $((OPTIND -1))
@@ -67,22 +69,23 @@ knowngood_failed() {
 	err1="$1"; err2="$2"
 	echo ""
 	echo "$err1" >&2; echo "$err2" >&2
+	# print errors to syslog
 	logger -t geoblocker_bash-apply "$err1"; logger -t geoblocker_bash-apply "$err2"
 	geoblocker_bash-uninstall -p
 	exit 1
 }
 
-# fail2ban doesn't handle well flushing INPUT chain then restoring iptables
-# this function is used to restart fail2ban service after these operations to work around that issue
+# fail2ban doesn't handle well flushing the INPUT chain then restoring iptables
+# this function restarts fail2ban service after these operations in order to work around that issue
 restart_fail2ban() {
 	systemctl is-enabled fail2ban &> /dev/null; rv=$?
 	if [ $rv -eq 0 ]; then
-		[ $debug ] && echo -n "Debug: Restarting fail2ban..."
+		echo -n "Restarting fail2ban..." >&2
 		systemctl restart fail2ban; rv=$?
 		if [ $rv -eq 0 ]; then
-			[ $debug ] && echo "Ok."
+			echo "Ok." >&2
 		else
-			[ $debug ] && echo "Failed."
+			echo "Failed." >&2
 		fi
 	fi
 }
@@ -146,7 +149,7 @@ restore_knowngood_ipset() {
 	# if we are here then something is seriously broken
 	# run the uninstall script with -p switch to restore iptables to pre-install state but leave files in place
 	err2="*** Rolling back all changes to iptables to pre-install state and removing cron jobs ***"
-	
+
 	# if the -t switch wasn't specified at launch then it's not a test. proceed to 2nd stage of fault recovery.
 	[ ! $test ] && knowngood_failed "$err1" "$err2"
 	echo ""; echo ""
@@ -212,18 +215,21 @@ fi
 # Check that we have the ipset utility
 if ! command -v "ipset" &> /dev/null; then
 	err="Error: Cannot find 'ipset'. Install it with 'apt install ipset' or similar. Exiting."
+	echo ""
 	die "$err"
 fi
 
 # Check that we have the iptables-save utility
 if ! command -v "iptables-save" &> /dev/null; then
 	err="Error: Cannot find 'iptables-save'. Exiting."
+	echo ""
 	die "$err"
 fi
 
 # Check that we have the iptables-restore utility
 if ! command -v "iptables-restore" &> /dev/null; then
 	err="Error: Cannot find 'iptables-restore'. Exiting."
+	echo ""
 	die "$err"
 fi
 
@@ -248,6 +254,7 @@ echo -n "Temporarily setting INPUT chain policy to ACCEPT... "
 iptables -P INPUT ACCEPT; rv=$?
 if [ $rv -ne 0 ]; then
 	err="Error $rv trying to change iptables policy with command \"iptables -P INPUT ACCEPT\". Exiting."
+	echo ""
 	die "$err"
 fi
 echo "Ok."
@@ -265,6 +272,7 @@ iptables-save | sed -r "/INPUT.*comment.*$iptables_comment/s/-A/iptables -D/e" &
 if [ $rv -ne 0 ]; then
 	echo "Failure."
 	err="Error $rv trying to remove existing rules with command: iptables-save | sed -r \"/INPUT.*comment.*$iptables_comment/s/-A/iptables -D/e\". Exiting."
+	echo ""
 	die "$err"
 fi
 echo "Ok."
@@ -282,6 +290,7 @@ if [ $ipset_length -ge "7" ]; then
 	ipset destroy "$ipset_name"; rv=$?
 	if [ $rv -ne 0 ]; then
 		err="Error $rv destroying ipset \"$ipset_name\". Exiting."
+		echo ""
 		die "$err"
 	fi
 	echo "Ok."
@@ -297,6 +306,7 @@ echo -n "Creating new ipset \"$ipset_name\"... "
 ipset create "$ipset_name" hash:net family "$family"; rv=$?
 if [ $rv -ne 0 ]; then
 	err="Error $rv trying to create ipset \"$ipset_name\". Exiting."
+	echo ""
 	die "$err"
 fi
 echo "Ok."
@@ -307,6 +317,7 @@ for ip in `cat $whitelist_path`; do
 	ipset add "$ipset_name" "$ip"; rv=$?
 	if [ $rv -ne 0 ]; then
 		err="Error $rv trying to run the command: \"ipset add $ipset_name $ip\". Exiting."
+		echo ""
 		die "$err"
 	fi
 done
@@ -316,6 +327,7 @@ echo -n "Inserting rule to allow all traffic from the loopback interface... "
 iptables -I INPUT -i lo -j ACCEPT -m comment --comment "$iptables_comment"; rv=$?
 if [ $rv -ne 0 ]; then
 	err="Error $rv trying to insert rules with command \"iptables -A INPUT -i lo -j ACCEPT\". Exiting."
+	echo ""
 	die "$err"
 fi
 echo "Ok."
@@ -325,6 +337,7 @@ echo -n "Inserting rule to allow established/related connections... "
 iptables -I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT -m comment --comment "$iptables_comment"; rv=$?
 if [ $rv -ne 0 ]; then
 	err="Error $rv trying to insert rules with command \"iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT\". Exiting."
+	echo ""
 	die "$err"
 fi
 echo "Ok."
@@ -334,6 +347,7 @@ echo -n "Appending the whitelist rule to the INPUT chain... "
 iptables -A INPUT -m set --match-set "$ipset_name" src -j ACCEPT -m comment --comment "$iptables_comment"; rv=$?
 if [ $rv -ne 0 ]; then
 	err="Error $rv trying to append ipset rules with command \"iptables -I INPUT -m set --match-set "$ipset_name" src -j ACCEPT\". Exiting."
+	echo ""
 	die "$err"
 fi
 echo "Ok."
@@ -345,12 +359,14 @@ echo -n "Setting default iptables policies for INPUT and FORWARD to DROP... "
 iptables -P INPUT DROP; rv=$?
 if [ $rv -ne 0 ]; then
 	err="Error $rv trying to change iptables policy with command \"iptables -P INPUT DROP\". Exiting."
+	echo ""
 	die "$err"
 fi
 
 iptables -P FORWARD DROP; rv=$?
 if [ $rv -ne 0 ]; then
 	err="Error $rv trying to change iptables policy with command \"iptables -P FORWARD DROP\". Exiting."
+	echo ""
 	die "$err"
 fi
 echo "Ok."
@@ -376,19 +392,21 @@ echo -n "Creating backup of current ipset... "
 echo "[IPSET]" >> "$knowngood_file.new"
 ipset save "$ipset_name" >> "$knowngood_file.new"; rv=$?
 if [ $rv -ne 0 ]; then
+	echo ""
 	echo "Error $rv saving backup of ipset \"$ipset_name\". Exiting."
 	echo ""
 	exit 1
 fi
 echo "Ok."
 
+echo "Backup file: \"$knowngood_file\""
+
 mv "$knowngood_file.new" "$knowngood_file"; rv=$?
 if [ $rv -ne 0 ]; then
-	echo "Error $rv while trying to overwrite backup file of iptables state. Exiting." >&2
+	echo "Error $rv while trying to overwrite backup file for ipset and iptables state. Exiting." >&2
 	echo ""
 	exit 1
 fi
-echo "Backup file location: $knowngood_file"
 echo ""
 
 echo "Successfully applied new iptables rules."
