cosmetic improvement to the "usage" function

diff --git a/geoblocker_bash-run b/geoblocker_bash-run
--- a/geoblocker_bash-run
+++ b/geoblocker_bash-run
@@ -5,7 +5,6 @@
 
 
 me=$(basename "$0")
-echo ""
 
 #### FUNCTIONS
 
@@ -15,11 +14,12 @@ usage() {
     Usage: $me -c country [-p path] [-d] [-h]
 
     Options:
-                -c tld		: tld / country code
-	        -p path		: Path to store downloaded ip lists (default: /var/lib/geoblocker_bash)
+		-c tld		: tld / country code
+		-p path		: Path to store downloaded ip lists (default: /var/lib/geoblocker_bash)
 
-                -d		: Debug
-                -h		: This help
+		-d		: Debug
+		-h		: This help
+
 EOF
 }
 
@@ -30,16 +30,14 @@ die() {
 	exit 1
 }
 
-
-
 #### PARSE ARGUMENTS
 
 while getopts "c:p:dh" opt; do
     case $opt in
-                c) country=$OPTARG;;
+		c) country=$OPTARG;;
 		p) whitelist_path=$OPTARG;;
-                d) debug="-d";;
-                h) usage;;
+		d) debug="-d";;
+		h) usage; exit 0;;
     esac
 done
 shift $((OPTIND -1))
@@ -47,33 +45,31 @@ shift $((OPTIND -1))
 
 #### Initialize variables
 
-min_size_ipv4=${min_size_ipv4:-5000}  # default is 5000 bytes
-min_size_ipv6=${min_size_ipv6:-2000}  # default is 2000 bytes
 whitelist_path=${whitelist_path:-/var/lib/geoblocker_bash}  # default is /var/lib/geoblocker_bash
 
+echo ""
 
 #### Checks
 
 # check that we have geoblocker_bash-fetch
 if ! command -v geoblocker_bash-fetch &> /dev/null; then
-        err="Error: Cannot find \"geoblocker_bash-fetch\". Did you run setup? Exiting."
-        die "$err"
+	err="Error: Cannot find \"geoblocker_bash-fetch\". Did you run setup? Exiting."
+	die "$err"
 fi
 
 # check that we have geoblocker_bash-apply
 if ! command -v geoblocker_bash-apply &> /dev/null; then
-        err="Error: Cannot find \"geoblocker_bash-apply\". Did you run setup? Exiting."
-        die "$err"
+	err="Error: Cannot find \"geoblocker_bash-apply\". Did you run setup? Exiting."
+	die "$err"
 fi
 
 
 if [ -z "$country" ]; then
-        err="Specify country with -c! Exiting."
+	err="Specify country with -c! Exiting."
 	usage
 	echo ""
-        die "$err"
+	die "$err"
 fi
-
 
 
 #### Main
@@ -86,12 +82,12 @@ else
 	[ $debug ] && echo "Successfully retrieved ip list from RIPE."
 fi
 
-geoblocker_bash-apply $debug -p "$whitelist_path/ipv4_$country" -o; rv=$?
+geoblocker_bash-apply $debug -p "$whitelist_path/ipv4_$country"; rv=$?
 if [ $rv -ne 0 ]; then
-        echo ""
-        exit $rv
+	echo ""
+	exit $rv
 else
-        [ $debug ] && echo "Successfully applied the whitelist."
+	[ $debug ] && echo "Successfully applied the whitelist."
 fi
 
 logger -t geoblocker_bash-run "Successfully fetched and applied whitelist."
