*fetch: - increased connection timeout time from 5s to 7s - improved error handling logic when download fails for different reasons - reject lists with 0 validated subnets - improved some error messages

diff --git a/geoblocker-bash-fetch b/geoblocker-bash-fetch
--- a/geoblocker-bash-fetch
+++ b/geoblocker-bash-fetch
@@ -82,8 +82,9 @@ shift $((OPTIND -1))
 
 [[ "$*" != "" ]] && {
 	usage
-	die "Error in arguments. First unrecognized argument: '$1'."
-	exit 1
+	err1="Error in arguments. First unrecognized argument: '$1'."
+	err2="Note: If specifying multiple country codes, put them between double quotation marks."
+	die "err1" "err2"
 }
 
 # get debugmode variable from either the args or environment variable, depending on what's set
@@ -107,8 +108,8 @@ ip_regex='^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}'
 mask_regex='(/([01]?\d\d?|2[0-4]\d|25[0-5]))$'
 subnet_regex="${ip_regex}${mask_regex}"
 
-curl_command="curl --retry 8 --fail-early --connect-timeout 5 --progress-bar"
-wget_command="wget --tries=8 --timeout=5 --show-progress"
+curl_command="curl --retry 8 --fail-early --connect-timeout 7 --progress-bar"
+wget_command="wget --tries=8 --timeout=7 --show-progress"
 
 apply_tlds=""
 failed_tlds=""
@@ -116,6 +117,7 @@ failed_tlds=""
 fetch_retries=3
 
 status_file="$iplist_dir/status"
+
 
 #### Checks
 
@@ -169,6 +171,8 @@ for tld in $tlds; do
 	parsed_subnets_cnt=0
 	old_failed_subnets_cnt=""
 
+	echo -e "Fetching subnets list for country '$tld'...\n"
+
 	# Make $fetch_retries attempts to fetch the list for each TLD (or until successful fetch and no validation errors)
 	while true; do
 		retry_cnt=$(( retry_cnt + 1 ))
@@ -179,78 +183,78 @@ for tld in $tlds; do
 			fetch_command="$curl_command $url -o $fetched_file"
 		fi
 
-		# debugprint "Trying: $curl_or_wget '$ripe_url$tld'" >&2
-		echo -e "Fetching iplist from RIPE for country '$tld'... \n"
-
 		$fetch_command; rv=$?
 
 		if [ $rv -ne 0 ]; then
 			rm "$fetched_file" &>/dev/null
-			die 254 "Error when running $fetch_command."
-		fi
-
-		status=$(jq -r '.status' "$fetched_file")
-		if [ ! "$status" = "ok" ]; then
-			echolog -err "Failed to fetch the list for country '$tld'."
-			ripe_msg=$(jq -r -c '.messages' "$fetched_file")
-			debugprint "RIPE replied with message: '$ripe_msg'"
-			rm "$fetched_file" &>/dev/null
 			tld_status="failed"
-		fi
-
-		echo -e "\nFetch successful.\n"
-
-		# get the date of the fetched file
-		ripe_db_time=$(jq -r '.data.query_time' "$fetched_file")
-		date_new=$(date -d "$ripe_db_time" +%s)
-
-		# skip list update if data timestamp didn't change, and there were no validation errors in the old list,
-		# and we are not in manual mode, and force_update wasn't requested
-		if [[ "$old_list_exists" &&  "$date_new" -le "$date_old" && "$force_update" != "true" && \
-						"$manualmode" != "true" && "$old_failed_subnets_cnt" -eq 0 ]]; then
-			echolog "Subnets list for country '$tld' is already up-to-date. Timestamp: '$(date --date=@$date_new)'."
-			tld_status="up_to_date"
-			rm "$fetched_file" &>/dev/null
-			break
-		fi
-
-		parsed_file=$(mktemp "/tmp/parsed-$tld-XXXX.list")
-
-		# Parse the fetched file
-		echo -n "Parsing... "
-		jq -r ".data.resources.$family | .[]" "$fetched_file" > "$parsed_file"; rv=$?
-
-		rm "$fetched_file" &>/dev/null
-
-		if [ "$rv" -ne 0 ]; then
-			rm "$parsed_file" &>/dev/null
-			tld_status="failed"
-			echolog "Error: failed to parse the fetched file for country '$tld'."
-			[ "$retry_cnt" -ge "$fetch_retries" ] && break || echolog "Retrying fetch..." >&2
+			echolog "Error when running '$fetch_command'."
+			[ "$retry_cnt" -ge "$fetch_retries" ] && break
 		else
-			echo "Ok."
-			# Validate the parsed file
-			parsed_subnets_cnt=$(wc -l < "$parsed_file")
-
-			echo -n "Validating... "
-			validated_file=$(mktemp "/tmp/validated-$tld-XXXX.list")
-			grep -P "$subnet_regex" "$parsed_file" > "$validated_file"
-			rm "$parsed_file" &>/dev/null
-
-			validated_subnets_cnt=$(wc -l < "$validated_file")
-
-			failed_subnets_cnt=$(( parsed_subnets_cnt - validated_subnets_cnt ))
-			if [ "$failed_subnets_cnt" -gt 0 ]; then
-				echo "Note: Fetch attempt $retry_cnt for country '$tld': $failed_subnets_cnt subnets failed validation." >&2
-				[ "$retry_cnt" -ge "$fetch_retries" ] && { tld_status="partial"; break; }
-				rm "$validated_file" &>/dev/null
-				echolog "Retrying fetch..." >&2
+			status=$(jq -r '.status' "$fetched_file")
+			if [[ ! "$status" = "ok" || ! -s "$fetched_file" ]]; then
+				echolog -err "Failed to fetch subnets list for country '$tld'."
+				ripe_msg=$(jq -r -c '.messages' "$fetched_file")
+				debugprint "RIPE replied with message: '$ripe_msg'"
+				rm "$fetched_file" &>/dev/null
+				tld_status="failed"
+				[ "$retry_cnt" -ge "$fetch_retries" ] && break
 			else
-				echo "Ok."
-				tld_status="Ok"
-				break
+				echo "Fetch successful."
+
+				# get the date of the fetched file
+				ripe_db_time=$(jq -r '.data.query_time' "$fetched_file")
+				date_new=$(date -d "$ripe_db_time" +%s)
+
+				# skip list update if data timestamp didn't change, and there were no validation errors in the old list,
+				# and we are not in manual mode, and force_update wasn't requested
+				if [[ "$old_list_exists" &&  "$date_new" -le "$date_old" && "$force_update" != "true" && \
+								"$manualmode" != "true" && "$old_failed_subnets_cnt" -eq 0 ]]; then
+					echolog "Subnets list for country '$tld' is already up-to-date. Timestamp: '$(date --date=@$date_new)'."
+					tld_status="up_to_date"
+					rm "$fetched_file" &>/dev/null
+					break
+				fi
+
+				parsed_file=$(mktemp "/tmp/parsed-$tld-XXXX.list")
+
+				# Parse the fetched file
+				echo -n "Parsing... "
+				jq -r ".data.resources.$family | .[]" "$fetched_file" > "$parsed_file"; rv=$?
+
+				rm "$fetched_file" &>/dev/null
+
+				if [ "$rv" -ne 0 ]; then
+					rm "$parsed_file" &>/dev/null
+					tld_status="failed"
+					echolog -err "Error: failed to parse the fetched file for country '$tld'."
+					[ "$retry_cnt" -ge "$fetch_retries" ] && break
+				else
+					echo "Ok."
+					# Validate the parsed file
+					parsed_subnets_cnt=$(wc -l < "$parsed_file")
+
+					echo -n "Validating... "
+					validated_file=$(mktemp "/tmp/validated-$tld-XXXX.list")
+					grep -P "$subnet_regex" "$parsed_file" > "$validated_file"
+					rm "$parsed_file" &>/dev/null
+
+					validated_subnets_cnt=$(wc -l < "$validated_file")
+
+					failed_subnets_cnt=$(( parsed_subnets_cnt - validated_subnets_cnt ))
+					if [ "$failed_subnets_cnt" -gt 0 ]; then
+						echolog -err "Note: Fetch attempt $retry_cnt for country '$tld': $failed_subnets_cnt subnets failed validation."
+						[ "$retry_cnt" -ge "$fetch_retries" ] && { tld_status="partial"; break; }
+						rm "$validated_file" &>/dev/null
+					else
+						echo "Ok."
+						tld_status="Ok"
+						break
+					fi
+				fi
 			fi
 		fi
+		echo -e "Retrying fetch for country '$tld'...\n"
 	done
 
 	# Check if subnets count decreased dramatically compared to the old list
@@ -272,7 +276,7 @@ for tld in $tlds; do
 
 	# If we have a partial list, decide whether to consider it Ok or not
 	if [ "$tld_status" = "partial" ]; then
-			echolog -err "Warning: $failed_subnets_cnt subnets for country '$tld' failed validation."
+			echolog -err "Warning: out of $parsed_subnets_cnt, $failed_subnets_cnt subnets for country '$tld' failed validation."
 			echolog -err "Invalid subnets removed from the list."
 
 		if [ "$old_list_exists" = "true" ]; then
@@ -306,6 +310,14 @@ for tld in $tlds; do
 		fi
 	fi
 
+	echo
+
+	if [[ "$tld_status" = "Ok" && "$validated_subnets_cnt" -eq 0 ]]; then
+		rm "$validated_file" &>/dev/null
+		echolog "Error: validated 0 subnets for country '$tld'. Perhaps the country code is incorrect?" >&2
+		tld_status="failed"
+	fi
+
 	if [[ "$tld_status" = "Ok" || "$tld_status" = "partial" ]]; then
 		echo -e "Validated subnets count for country '$tld': $validated_subnets_cnt.\n"
 	fi
@@ -337,7 +349,6 @@ for tld in $tlds; do
 	fi
 
 	rm "$validated_file" &>/dev/null
-
 done
 
 # report fetch results back to *run via the config file
