*uninstall: minor code cleanup

diff --git a/geoblocker-bash-uninstall b/geoblocker-bash-uninstall
--- a/geoblocker-bash-uninstall
+++ b/geoblocker-bash-uninstall
@@ -18,8 +18,11 @@ me=$(basename "$0")
 
 suite_name="geoblocker-bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-[ -n "$script_dir" ] && cd "$script_dir" || { echo "Error: Couldn't cd into '$script_dir'. Exiting." >&2; exit 1; }
-source "$script_dir/${suite_name}-common" || { echo "Error: Can't find ${suite_name}-common. Exiting." >&2; exit 1; }
+[ -n "$script_dir" ] && cd "$script_dir" || { echo "Error: Couldn't cd into '$script_dir'." >&2; exit 1; }
+
+source "$script_dir/${suite_name}-common" || { echo "Error: Can't source ${suite_name}-common." >&2; exit 1; }
+
+# **NOTE** that some functions and variables are sourced from the *common script
 
 
 #### USAGE
@@ -145,6 +148,4 @@ rm "$install_dir/${suite_name}-backup"
 echo "Deleting config..."
 rm -rf "$conf_dir"
 
-echo "Uninstall complete."
-
-echo ""
+echo -e "Uninstall complete.\n"
