*manage: - specifically call the die() function with -nolog option on init when an error occurs - check for valid list type - some code cleanup

diff --git a/geoblocker-bash-manage b/geoblocker-bash-manage
--- a/geoblocker-bash-manage
+++ b/geoblocker-bash-manage
@@ -69,7 +69,7 @@ shift 1
 # check for valid action
 case "$action" in
 	add | remove | schedule | status ) ;;
-	* ) err1="Error: Unrecognized action: '$action'."; err2="Specify action in the 1st argument!"; die "$err1" "$err2" ;;
+	* ) err1="Error: Unrecognized action: '$action'."; err2="Specify action in the 1st argument!"; die -nolog "$err1" "$err2" ;;
 esac
 
 # process the rest of the arguments
@@ -134,6 +134,7 @@ report_status() {
 			echo "WARNING: blacklist functionality requires INPUT chain policy to be 'ACCEPT' but it is '$current_input_policy'."
 			echo "Essentially, connections from all countries are being blocked which is probably not what you want.";
 			} || echo "Current INPUT chain policy is compatible with blacklist." ;;
+		*) die "Error: unrecognized list type '$list_type'!"
 	esac
 
 	if [ "$list_type" = "whitelist" ]; then
@@ -257,10 +258,12 @@ export nolog="true"
 export manualmode="true"
 
 # get install_dir from the config file
-install_dir="$(getconfig "Installdir")" || { die "Error: Couldn't read value for Installdir from the config file."; }
+install_dir="$(getconfig "Installdir")" || die "Error: Couldn't read value for Installdir from the config file."
 
 # get list_type from the config file
-list_type="$(getconfig "ListType")" || { die "Error: Couldn't read value for ListType from the config file."; }
+list_type="$(getconfig "ListType")" || die "Error: Couldn't read value for ListType from the config file."
+
+[ "$list_type" != "whitelist" && "$list_type" != "blacklist" ] &&  die "Error: Unrecognized list type '$list_type'!"
 
 # convert input country codes (tlds) to lower case
 tlds_arg="${tlds_arg,,}"
@@ -269,7 +272,7 @@ tlds_arg="${tlds_arg,,}"
 tlds_arg="$(sanitize_string "$tlds_arg")"
 
 ### Read current set of countries from the the config file into config_tlds
-config_tlds="$(getconfig "Countries")" || { die "Error: Couldn't read value for Countries from the config file."; }
+config_tlds="$(getconfig "Countries")" || die "Error: Couldn't read value for Countries from the config file."
 
 # convert the string to lower case
 action="${action,,}"
