*backup: - avoid writing some errors to syslog when run in manual mode - improved error message when invalid action is specified

diff --git a/geoblocker-bash-backup b/geoblocker-bash-backup
--- a/geoblocker-bash-backup
+++ b/geoblocker-bash-backup
@@ -18,15 +18,20 @@ me=$(basename "$0")
 [ "$EUID" -ne 0 ] && {
 	err="Error: $me needs to be run as root."
 	echo "$err" >&2
+	[ ! "$manualmode" ] && logger "$err"
 	exit 1
 }
 
 suite_name="geoblocker-bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-[ -n "$script_dir" ] && cd "$script_dir" || { echo "Error: Couldn't cd into '$script_dir'." >&2; exit 1; }
+[ -n "$script_dir" ] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
+	[ ! "$manualmode" ] && logger "$err"; exit 1; }
 
-source "$script_dir/${suite_name}-common" || { echo "Error: Can't find ${suite_name}-common." >&2; exit 1; }
+source "$script_dir/${suite_name}-common" || { err="$me: Error: Can't source ${suite_name}-common."; echo "$err" >&2; \
+	[ ! "$manualmode" ] && logger "$err"; exit 1; }
+
 # **NOTE** that some functions and variables are sourced from the *common script
+
 
 # sanitize arguments
 sanitize_args "$@"
@@ -63,6 +68,13 @@ EOF
 action="$1"
 shift 1
 
+# check for valid action
+case "$action" in
+	create-backup | restore ) ;;
+	* ) err1="Error: Unrecognized action: '$action'."; err2="Specify action in the 1st argument!"; die "$err1" "$err2" ;;
+esac
+
+# process the rest of the arguments
 while getopts ":dh" opt; do
 	case $opt in
 		d) debugmode_args="true";;
