*fetch: a couple minor improvements - compacted some code - exit with error if neither curl nor wget were found

diff --git a/geoblocker_bash-fetch b/geoblocker_bash-fetch
--- a/geoblocker_bash-fetch
+++ b/geoblocker_bash-fetch
@@ -86,33 +86,25 @@ subnet_regex="${ip_regex}${mask_regex}"
 
 #### Checks
 
-if [ -z "$country" ]; then
-	usage
-	die 1 "Specify country with '-c <country>'!"
-fi
+[ -z "$country" ] && { usage; die 1 "Specify country with '-c <country>'!"; }
 
 # check that we have iplist file path
-if [ -z "$iplist_path" ]; then
-	usage
-	die 1 "Specify iplist file path with '-p <path-to-file>'!"
-fi
+[ -z "$iplist_path" ] && { usage; die 1 "Specify iplist file path with '-p <path-to-file>'!"; }
 
 # use curl or wget, depending on which one we find
 if hash curl 2>/dev/null; then
 	curl_or_wget="curl -s --retry 4 --fail-early --connect-timeout 7"
 elif hash wget 2>/dev/null; then
 	curl_or_wget="wget --tries=4 --timeout=7 -qO-"
+else
+	die 1 "Error: Neither curl nor wget found."
 fi
 
 # check that we have jq
-if ! command -v jq &> /dev/null; then
-	die 1 "Error: Cannot find 'jq' - Json processor. Install it with 'apt install jq' or similar. Exiting"
-fi
+! command -v jq &> /dev/null && die 1 "Error: Can not find 'jq' - Json processor. Install it with 'apt install jq' or similar."
 
 # check that iplist directory exists
-if [ ! -d "$iplist_path" ]; then
-	die 1 "Directory '$iplist_path' doesn't exist!"
-fi
+[ ! -d "$iplist_path" ] && die 1 "Directory '$iplist_path' doesn't exist!"
 
 #### Main
 
@@ -121,8 +113,7 @@ fetched_file=$(mktemp "/tmp/fetched-$country-XXXX.json")
 # debugprint "Trying: $curl_or_wget '$url'" >&2
 echo -n "Fetching iplist from RIPE for country '$country'... "
 
-$curl_or_wget "$url" > "$fetched_file"
-rv=$?
+$curl_or_wget "$url" > "$fetched_file"; rv=$?
 
 if [ $rv -ne 0 ]; then
 	echo "Failed."
