minor code fixes
- double quoted some variables per shellcheck recommendations
- improved arithmetic expressions per shellcheck recommendations
- improved console output messages in debug mode
- skip timestamp check when in debug mode

diff --git a/geoblocker_bash-fetch b/geoblocker_bash-fetch
--- a/geoblocker_bash-fetch
+++ b/geoblocker_bash-fetch
@@ -54,7 +54,7 @@ validate_ipv4_subnet() {
 # regex compiled from 2 suggestions found here:
 # https://stackoverflow.com/questions/5284147/validating-ipv4-addresses-with-regexp
 	regex_pattern='^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}(/([01]?\d\d?|2[0-4]\d|25[0-5]))$'
-	echo "$1" | grep -P $regex_pattern; rv=$?
+	echo "$1" | grep -P "$regex_pattern"; rv=$?
 	# outputs grep result, effectively filtering out invalid subnets
 
 	return $rv
@@ -141,6 +141,7 @@ fi
 tmpfile=$(mktemp "/tmp/ripe-$country-XXXX.json")
 
 echo -n "Fetching iplist from RIPE... "
+[ $debug ] && echo ""
 [ $debug ] && echo "Debug: Trying: $curl_or_wget '$url'" >&2
 
 $curl_or_wget "$url" > "$tmpfile"
@@ -153,9 +154,9 @@ if [ $rv -ne 0 ]; then
 fi
 
 
-status=$(jq -r '.status' $tmpfile)
+status=$(jq -r '.status' "$tmpfile")
 if [ ! "$status" = "ok" ]; then
-	ripe_msg=$(jq -r -c '.messages' $tmpfile)
+	ripe_msg=$(jq -r -c '.messages' "$tmpfile")
 	echo "Failed."
 	echo "Error: RIPE replied with status = '$status'."
 	echo "The requested url was '$url'"
@@ -166,7 +167,7 @@ fi
 
 echo "Success."
 
-ripe_db_time=$(jq -r '.data.query_time' $tmpfile)
+ripe_db_time=$(jq -r '.data.query_time' "$tmpfile")
 [ $debug ] && echo "Debug: ripe_db_time=$ripe_db_time" >&2
 date_new=$(date -d "$ripe_db_time" +%s)
 
@@ -185,17 +186,16 @@ else
 	date_old=0
 fi
 
-if [ ! $date_new -gt $date_old ]; then
+if [ ! "$date_new" -gt "$date_old" ] && [ ! "$debug" ]; then
 	echo "Note: Not updating $filename because data querytime did not change: $date_old ($(date --date=@$date_old))." >&2
 else
-	[ $debug ]  && echo "Debug: Querytime changed, updating..."
 	errorcount=0
 	subnetcount=0
 	echo -n "Parsing and validating downloaded subnets... "
 	for testsubnet in $(jq -r ".data.resources.$family | .[]" "$tmpfile"); do
 		validate_ipv4_subnet "$testsubnet" >> "$out_list.new"; rv=$?
-		errorcount=$(($errorcount + $rv))
-		subnetcount=$(($subnetcount + 1))
+		errorcount=$((errorcount + rv))
+		subnetcount=$((subnetcount + 1))
 	done
 
 	if [ $errorcount -ne 0 ]; then
@@ -208,7 +208,7 @@ else
 		echo "Success."
 	fi
 
-	echo "Total validated subnets: $(($subnetcount - $errorcount))"
+	echo "Total validated subnets: $((subnetcount - errorcount))"
 	echo ""
 	touch -d "$ripe_db_time" "$out_list.new"
 
