*run: - avoid writing some errors to syslog when run in manual mode - improved error message when invalid action is specified

diff --git a/geoblocker-bash-run b/geoblocker-bash-run
--- a/geoblocker-bash-run
+++ b/geoblocker-bash-run
@@ -21,16 +21,20 @@ me=$(basename "$0")
 [ "$EUID" -ne 0 ] && {
 	err="Error: $me needs to be run as root."
 	echo "$err" >&2
-	logger "$err"
+	[ ! "$manualmode" ] && logger "$err"
 	exit 1
 }
 
 suite_name="geoblocker-bash"
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-[ -n "$script_dir" ] && cd "$script_dir" || { echo "Error: Couldn't cd into '$script_dir'." >&2; exit 1; }
+[ -n "$script_dir" ] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
+	[ ! "$manualmode" ] && logger "$err"; exit 1; }
 
-source "$script_dir/${suite_name}-common" || { echo "Error: Can't source ${suite_name}-common." >&2; exit 1; }
-# NOTE that some functions and variables are sourced from the *common script
+source "$script_dir/${suite_name}-common" || { err="$me: Error: Can't source ${suite_name}-common."; echo "$err" >&2; \
+	[ ! "$manualmode" ] && logger "$err"; exit 1; }
+
+# **NOTE** that some functions and variables are sourced from the *common script
+
 
 # sanitize arguments
 sanitize_args "$@"
@@ -70,6 +74,13 @@ EOF
 action_run="$1"
 shift 1
 
+# check for valid action
+case "$action_run" in
+	add | remove | update ) ;;
+	* ) err1="Error: Unrecognized action: '$action_run'."; err2="Specify action in the 1st argument!"; die "$err1" "$err2" ;;
+esac
+
+# process the rest of the arguments
 while getopts ":c:osdh" opt; do
 	case $opt in
 		c) arg_tlds=$OPTARG;;
@@ -77,7 +88,7 @@ while getopts ":c:osdh" opt; do
 		o) nobackup="true";;
 		d) debugmode_args="true";;
 		h) usage; exit 0;;
-		\?) usage; echo "Error: Unknown option: '-$OPTARG'." >&2; exit 1;;
+		\?) usage; die "Error: Unknown option: '$OPTARG'." ;;
 	esac
 done
 shift $((OPTIND -1))
